import * as cdk from 'aws-cdk-lib';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import * as cloudwatch_actions from 'aws-cdk-lib/aws-cloudwatch-actions';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as kms from 'aws-cdk-lib/aws-kms';
import { Construct } from 'constructs';

export class MoroBackendStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // SECURITY: Require JWT_SECRET to be set - never deploy with a hardcoded secret
    if (!process.env.JWT_SECRET) {
      throw new Error(
        'JWT_SECRET environment variable is required for deployment.\n' +
        'Generate one with: export JWT_SECRET=$(openssl rand -hex 32)\n' +
        'Then run: npx cdk deploy'
      );
    }

    const tablePrefix = this.node.tryGetContext('tablePrefix') || 'moro';

    // Cognito User Pool
    const userPool = new cognito.UserPool(this, 'MoroUserPool', {
      userPoolName: `${tablePrefix}-user-pool`,
      signInAliases: {
        email: true,
        username: true,
      },
      // Enable optional MFA (TOTP) for enhanced security
      mfa: cognito.Mfa.OPTIONAL,
      mfaSecondFactor: {
        otp: true,  // TOTP apps (Google Authenticator, Authy, etc.)
        sms: false, // SMS MFA disabled (costs money, less secure than TOTP)
      },
      selfSignUpEnabled: true, // Allow users to sign up themselves
      autoVerify: {
        email: true,
      },
      passwordPolicy: {
        minLength: 8,
        requireLowercase: true,
        requireUppercase: true,
        requireDigits: true,
        requireSymbols: false,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const userPoolClient = userPool.addClient('MoroUserPoolClient', {
      userPoolClientName: `${tablePrefix}-client`,
      generateSecret: false,
      authFlows: {
        userPassword: true,
        userSrp: true,
      },
    });

    // S3 Bucket for assets
    const assetsBucket = new s3.Bucket(this, 'MoroAssetsBucket', {
      bucketName: `${tablePrefix}-assets-${this.account}-${this.region}`,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      autoDeleteObjects: false,
      publicReadAccess: false, // Keep private for security
      // SECURITY: No CORS configuration for mobile-only API
      // S3 CORS is only needed for browser-based uploads, which we don't support
      // All access is via presigned URLs generated by the backend
      // Removing CORS entirely since empty origins array causes validation errors
    });

    // SECURITY: Removed public access to avatars folder
    // Avatars are now accessed via presigned URLs generated by the backend
    // This ensures only authenticated users can access avatar images
    // Old bucket policy removed - no public access allowed

    // KMS Key for DynamoDB encryption
    const dynamoDbEncryptionKey = new kms.Key(this, 'DynamoDbEncryptionKey', {
      description: 'KMS key for DynamoDB table encryption',
      enableKeyRotation: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // DynamoDB Tables
    const usersTable = new dynamodb.Table(this, 'UsersTable', {
      tableName: `${tablePrefix}-Users`,
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
    });

    const entitiesTable = new dynamodb.Table(this, 'EntitiesTable', {
      tableName: `${tablePrefix}-Entities`,
      partitionKey: { name: 'entityId', type: dynamodb.AttributeType.NUMBER },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });

    const portfoliosTable = new dynamodb.Table(this, 'PortfoliosTable', {
      tableName: `${tablePrefix}-Portfolios`,
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'entityId', type: dynamodb.AttributeType.NUMBER },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });

    const transactionsTable = new dynamodb.Table(this, 'TransactionsTable', {
      tableName: `${tablePrefix}-Transactions`,
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'timestamp', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });
    transactionsTable.addGlobalSecondaryIndex({
      indexName: 'entityId-timestamp-index',
      partitionKey: { name: 'entityId', type: dynamodb.AttributeType.NUMBER },
      sortKey: { name: 'timestamp', type: dynamodb.AttributeType.STRING },
    });

    const postsTable = new dynamodb.Table(this, 'PostsTable', {
      tableName: `${tablePrefix}-Posts`,
      partitionKey: { name: 'postId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });
    postsTable.addGlobalSecondaryIndex({
      indexName: 'userId-timestamp-index',
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'timestamp', type: dynamodb.AttributeType.STRING },
    });
    postsTable.addGlobalSecondaryIndex({
      indexName: 'entityId-timestamp-index',
      partitionKey: { name: 'entityId', type: dynamodb.AttributeType.NUMBER },
      sortKey: { name: 'timestamp', type: dynamodb.AttributeType.STRING },
    });

    const commentsTable = new dynamodb.Table(this, 'CommentsTable', {
      tableName: `${tablePrefix}-Comments`,
      partitionKey: { name: 'commentId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });
    commentsTable.addGlobalSecondaryIndex({
      indexName: 'postId-timestamp-index',
      partitionKey: { name: 'postId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'timestamp', type: dynamodb.AttributeType.STRING },
    });

    const followsTable = new dynamodb.Table(this, 'FollowsTable', {
      tableName: `${tablePrefix}-Follows`,
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'followingUserId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });

    const likesTable = new dynamodb.Table(this, 'LikesTable', {
      tableName: `${tablePrefix}-Likes`,
      partitionKey: { name: 'likeId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });
    likesTable.addGlobalSecondaryIndex({
      indexName: 'postId-userId-index',
      partitionKey: { name: 'postId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
    });

    const watchlistsTable = new dynamodb.Table(this, 'WatchlistsTable', {
      tableName: `${tablePrefix}-Watchlists`,
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'entityId', type: dynamodb.AttributeType.NUMBER },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });

    const newsArticlesTable = new dynamodb.Table(this, 'NewsArticlesTable', {
      tableName: `${tablePrefix}-NewsArticles`,
      partitionKey: { name: 'articleId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });
    newsArticlesTable.addGlobalSecondaryIndex({
      indexName: 'entityId-publishedAt-index',
      partitionKey: { name: 'entityId', type: dynamodb.AttributeType.NUMBER },
      sortKey: { name: 'publishedAt', type: dynamodb.AttributeType.STRING },
    });

    const priceHistoryTable = new dynamodb.Table(this, 'PriceHistoryTable', {
      tableName: `${tablePrefix}-PriceHistory`,
      partitionKey: { name: 'entityId', type: dynamodb.AttributeType.NUMBER },
      sortKey: { name: 'timestamp', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });

    const blocksTable = new dynamodb.Table(this, 'BlocksTable', {
      tableName: `${tablePrefix}-Blocks`,
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'blockedUserId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });

    const reportsTable = new dynamodb.Table(this, 'ReportsTable', {
      tableName: `${tablePrefix}-Reports`,
      partitionKey: { name: 'reportId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });

    const purchaseTransactionsTable = new dynamodb.Table(this, 'PurchaseTransactionsTable', {
      tableName: `${tablePrefix}-PurchaseTransactions`,
      partitionKey: { name: 'transactionId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });
    purchaseTransactionsTable.addGlobalSecondaryIndex({
      indexName: 'userId-createdAt-index',
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'createdAt', type: dynamodb.AttributeType.STRING },
    });

    const groupsTable = new dynamodb.Table(this, 'GroupsTable', {
      tableName: `${tablePrefix}-Groups`,
      partitionKey: { name: 'groupId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });

    const groupMembersTable = new dynamodb.Table(this, 'GroupMembersTable', {
      tableName: `${tablePrefix}-GroupMembers`,
      partitionKey: { name: 'groupId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });
    groupMembersTable.addGlobalSecondaryIndex({
      indexName: 'userId-groupId-index',
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'groupId', type: dynamodb.AttributeType.STRING },
    });

    // Notifications Table
    const notificationsTable = new dynamodb.Table(this, 'NotificationsTable', {
      tableName: `${tablePrefix}-Notifications`,
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'notificationId', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      pointInTimeRecovery: true, // Enable PITR for data recovery
      encryption: dynamodb.TableEncryption.CUSTOMER_MANAGED,
      encryptionKey: dynamoDbEncryptionKey,
    });
    // GSI for querying by read status and creation time
    notificationsTable.addGlobalSecondaryIndex({
      indexName: 'userId-createdAt-index',
      partitionKey: { name: 'userId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'createdAt', type: dynamodb.AttributeType.STRING },
    });

    // Separate role for pre-signup Lambda (to avoid circular dependencies)
    const preSignUpLambdaRole = new iam.Role(this, 'PreSignUpLambdaRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });

    // Pre-signup Lambda trigger for auto-confirming users
    const preSignUpLambda = new lambda.Function(this, 'PreSignUpLambda', {
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'src/handlers/cognitoTriggers.preSignUp',
      code: lambda.Code.fromAsset('bundle'),
      role: preSignUpLambdaRole,
      timeout: cdk.Duration.seconds(10),
    });

    // Add the pre-signup trigger to the user pool
    userPool.addTrigger(cognito.UserPoolOperation.PRE_SIGN_UP, preSignUpLambda);

    // Lambda execution role for API handlers
    // NOTE: Currently using a single role for all handlers due to single Lambda architecture
    // For better security, consider splitting into separate Lambda functions per domain
    // with domain-specific roles (authRole, tradingRole, socialRole, etc.)
    const lambdaRole = new iam.Role(this, 'LambdaExecutionRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });

    // Create separate IAM roles per domain for future use (when splitting Lambdas)
    // These roles are created but not currently used due to single Lambda limitation
    const authRole = new iam.Role(this, 'AuthRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });
    usersTable.grantReadWriteData(authRole);
    userPool.grant(authRole, 'cognito-idp:AdminCreateUser', 'cognito-idp:AdminGetUser', 'cognito-idp:AdminDeleteUser');

    const tradingRole = new iam.Role(this, 'TradingRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });
    usersTable.grantReadWriteData(tradingRole); // Need to read/update cash balance
    portfoliosTable.grantReadWriteData(tradingRole);
    transactionsTable.grantReadWriteData(tradingRole);
    entitiesTable.grantReadData(tradingRole);
    priceHistoryTable.grantReadWriteData(tradingRole);

    const socialRole = new iam.Role(this, 'SocialRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });
    usersTable.grantReadData(socialRole); // Need to read user profiles
    postsTable.grantReadWriteData(socialRole);
    commentsTable.grantReadWriteData(socialRole);
    likesTable.grantReadWriteData(socialRole);
    followsTable.grantReadWriteData(socialRole);
    blocksTable.grantReadWriteData(socialRole);
    reportsTable.grantReadWriteData(socialRole);
    assetsBucket.grantReadWrite(socialRole); // For post images

    const userRole = new iam.Role(this, 'UserRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });
    usersTable.grantReadData(userRole);
    watchlistsTable.grantReadWriteData(userRole);
    notificationsTable.grantReadWriteData(userRole);
    assetsBucket.grantReadWrite(userRole); // For avatars

    const contentRole = new iam.Role(this, 'ContentRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });
    newsArticlesTable.grantReadWriteData(contentRole);
    groupsTable.grantReadWriteData(contentRole);
    groupMembersTable.grantReadWriteData(contentRole);
    entitiesTable.grantReadData(contentRole); // For entity references

    // Grant Comprehend permissions to socialRole (for content moderation)
    socialRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['comprehend:DetectToxicContent'],
      resources: ['*'],
    }));

    // Grant KMS permissions for DynamoDB encryption to all roles
    dynamoDbEncryptionKey.grantDecrypt(lambdaRole);
    dynamoDbEncryptionKey.grantEncrypt(lambdaRole);
    dynamoDbEncryptionKey.grantDecrypt(authRole);
    dynamoDbEncryptionKey.grantEncrypt(authRole);
    dynamoDbEncryptionKey.grantDecrypt(tradingRole);
    dynamoDbEncryptionKey.grantEncrypt(tradingRole);
    dynamoDbEncryptionKey.grantDecrypt(socialRole);
    dynamoDbEncryptionKey.grantEncrypt(socialRole);
    dynamoDbEncryptionKey.grantDecrypt(userRole);
    dynamoDbEncryptionKey.grantEncrypt(userRole);
    dynamoDbEncryptionKey.grantDecrypt(contentRole);
    dynamoDbEncryptionKey.grantEncrypt(contentRole);

    // Grant permissions to main lambdaRole (currently used by single Lambda)
    usersTable.grantReadWriteData(lambdaRole);
    entitiesTable.grantReadWriteData(lambdaRole);
    portfoliosTable.grantReadWriteData(lambdaRole);
    transactionsTable.grantReadWriteData(lambdaRole);
    postsTable.grantReadWriteData(lambdaRole);
    commentsTable.grantReadWriteData(lambdaRole);
    followsTable.grantReadWriteData(lambdaRole);
    likesTable.grantReadWriteData(lambdaRole);
    watchlistsTable.grantReadWriteData(lambdaRole);
    newsArticlesTable.grantReadWriteData(lambdaRole);
    priceHistoryTable.grantReadWriteData(lambdaRole);
    blocksTable.grantReadWriteData(lambdaRole);
    reportsTable.grantReadWriteData(lambdaRole);
    purchaseTransactionsTable.grantReadWriteData(lambdaRole);
    groupsTable.grantReadWriteData(lambdaRole);
    groupMembersTable.grantReadWriteData(lambdaRole);
    notificationsTable.grantReadWriteData(lambdaRole);
    assetsBucket.grantReadWrite(lambdaRole);
    userPool.grant(lambdaRole, 'cognito-idp:AdminCreateUser', 'cognito-idp:AdminGetUser', 'cognito-idp:AdminDeleteUser');
    
    // Grant Comprehend permissions for content moderation
    lambdaRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'comprehend:DetectToxicContent',
      ],
      resources: ['*'], // Comprehend doesn't support resource-level permissions
    }));

    // Single Lambda function that handles all API requests
    // The handler routes to appropriate functions based on the path
    const apiLambda = new lambda.Function(this, 'ApiLambda', {
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'src/index.handler',
      code: lambda.Code.fromAsset('bundle'),
      role: lambdaRole,
      timeout: cdk.Duration.seconds(30),
      environment: {
        USERS_TABLE: usersTable.tableName,
        ENTITIES_TABLE: entitiesTable.tableName,
        PORTFOLIOS_TABLE: portfoliosTable.tableName,
        TRANSACTIONS_TABLE: transactionsTable.tableName,
        POSTS_TABLE: postsTable.tableName,
        COMMENTS_TABLE: commentsTable.tableName,
        FOLLOWS_TABLE: followsTable.tableName,
        LIKES_TABLE: likesTable.tableName,
        WATCHLISTS_TABLE: watchlistsTable.tableName,
        NEWS_ARTICLES_TABLE: newsArticlesTable.tableName,
        PRICE_HISTORY_TABLE: priceHistoryTable.tableName,
        BLOCKS_TABLE: blocksTable.tableName,
        REPORTS_TABLE: reportsTable.tableName,
        PURCHASE_TRANSACTIONS_TABLE: purchaseTransactionsTable.tableName,
        GROUPS_TABLE: groupsTable.tableName,
        GROUP_MEMBERS_TABLE: groupMembersTable.tableName,
        NOTIFICATIONS_TABLE: notificationsTable.tableName,
        COGNITO_USER_POOL_ID: userPool.userPoolId,
        COGNITO_CLIENT_ID: userPoolClient.userPoolClientId,
        S3_BUCKET_NAME: assetsBucket.bucketName,
        DYNAMODB_TABLE_PREFIX: tablePrefix,
        NEWS_API_KEY: process.env.NEWS_API_KEY || '', // Set via: export NEWS_API_KEY=your-key before deploy
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || '', // Set via: export GEMINI_API_KEY=your-key before deploy
        JWT_SECRET: process.env.JWT_SECRET!, // REQUIRED: Set via export JWT_SECRET=$(openssl rand -hex 32) before deploy
        APPLE_CLIENT_ID: process.env.APPLE_CLIENT_ID || 'com.moro.mobile', // Apple bundle identifier (defaults to app.json value)
        NODE_ENV: 'production', // SECURITY: Ensure production mode to prevent stack trace leakage
      },
    });

    // API Gateway
    // SECURITY: No CORS for mobile-only API (mobile apps don't use CORS)
    // If you need web access later, configure specific origins
    const api = new apigateway.RestApi(this, 'MoroApi', {
      restApiName: `${tablePrefix}-api`,
      description: 'Moro App API',
      // CORS disabled for mobile-only API - mobile apps don't use CORS
      // To enable web access, uncomment and specify allowed origins:
      // defaultCorsPreflightOptions: {
      //   allowOrigins: ['https://your-web-domain.com'],
      //   allowMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
      //   allowHeaders: ['Content-Type', 'Authorization'],
      // },
    });

    // Create API Gateway routes - use proxy integration to route all requests to single Lambda
    const apiResource = api.root.addResource('api');
    const proxyResource = apiResource.addProxy({
      defaultIntegration: new apigateway.LambdaIntegration(apiLambda),
      anyMethod: true,
    });

    // Also add root-level proxy for direct API calls
    const rootProxy = api.root.addProxy({
      defaultIntegration: new apigateway.LambdaIntegration(apiLambda),
      anyMethod: true,
    });

    // API Gateway Rate Limiting
    // SECURITY: Add throttling to prevent DoS and abuse
    // Note: API Gateway throttling applies per-IP for unauthenticated requests
    // The default account-level throttling is 10,000 requests/second, but we set stricter limits here
    // For mobile apps, throttling is per-IP address
    const usagePlan = new apigateway.UsagePlan(this, 'MoroUsagePlan', {
      name: 'Standard',
      throttle: {
        rateLimit: 100,  // 100 requests per second per IP
        burstLimit: 200, // Allow bursts up to 200 requests per IP
      },
      quota: {
        limit: 10000,  // 10,000 requests per day per IP
        period: apigateway.Period.DAY,
      },
    });

    // Create API key for additional security and rate limiting control
    const apiKey = api.addApiKey('MoroApiKey', {
      apiKeyName: `${tablePrefix}-api-key`,
      description: 'API key for Moro mobile app',
    });

    // Associate API key with usage plan
    usagePlan.addApiKey(apiKey);

    // Attach usage plan to the default stage
    // RestApi automatically creates a default deployment and stage
    // We use the default stage instead of creating a new one to avoid conflicts
    usagePlan.addApiStage({
      stage: api.deploymentStage,
    });

    // CloudWatch Alarms for monitoring
    // Create SNS topic for alert notifications
    const alertTopic = new sns.Topic(this, 'AlertTopic', {
      topicName: `${tablePrefix}-alerts`,
      displayName: 'Moro Backend Alerts',
    });

    // Alarm for high 5xx errors
    const high5xxErrorsAlarm = new cloudwatch.Alarm(this, 'High5xxErrors', {
      alarmName: `${tablePrefix}-high-5xx-errors`,
      metric: api.metricServerError({
        statistic: 'Sum',
        period: cdk.Duration.minutes(5),
      }),
      threshold: 10,
      evaluationPeriods: 2,
      datapointsToAlarm: 2,
      alarmDescription: 'High rate of 5xx server errors detected',
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });
    high5xxErrorsAlarm.addAlarmAction(new cloudwatch_actions.SnsAction(alertTopic));

    // Alarm for high latency (p99)
    const highLatencyAlarm = new cloudwatch.Alarm(this, 'HighLatency', {
      alarmName: `${tablePrefix}-high-latency`,
      metric: api.metricLatency({
        statistic: 'p99',
        period: cdk.Duration.minutes(5),
      }),
      threshold: 5000, // 5 seconds
      evaluationPeriods: 2,
      datapointsToAlarm: 2,
      alarmDescription: 'High API latency detected (p99 > 5s)',
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });
    highLatencyAlarm.addAlarmAction(new cloudwatch_actions.SnsAction(alertTopic));

    // Alarm for high 4xx errors (client errors - may indicate issues)
    const high4xxErrorsAlarm = new cloudwatch.Alarm(this, 'High4xxErrors', {
      alarmName: `${tablePrefix}-high-4xx-errors`,
      metric: api.metricClientError({
        statistic: 'Sum',
        period: cdk.Duration.minutes(5),
      }),
      threshold: 100, // 100 client errors in 5 minutes
      evaluationPeriods: 2,
      datapointsToAlarm: 2,
      alarmDescription: 'High rate of 4xx client errors detected',
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });
    high4xxErrorsAlarm.addAlarmAction(new cloudwatch_actions.SnsAction(alertTopic));

    // Outputs
    new cdk.CfnOutput(this, 'UserPoolId', {
      value: userPool.userPoolId,
      exportName: `${tablePrefix}-UserPoolId`,
    });

    new cdk.CfnOutput(this, 'UserPoolClientId', {
      value: userPoolClient.userPoolClientId,
      exportName: `${tablePrefix}-UserPoolClientId`,
    });

    new cdk.CfnOutput(this, 'ApiUrl', {
      value: api.url, // Use default API URL
      exportName: `${tablePrefix}-ApiUrl`,
      description: 'API Gateway URL - use this in EXPO_PUBLIC_API_URL',
    });

    new cdk.CfnOutput(this, 'AssetsBucketName', {
      value: assetsBucket.bucketName,
      exportName: `${tablePrefix}-AssetsBucketName`,
    });

    new cdk.CfnOutput(this, 'ApiKeyId', {
      value: apiKey.keyId,
      exportName: `${tablePrefix}-ApiKeyId`,
      description: 'API Key ID - retrieve the key value from AWS Console or CLI after deployment',
    });

    new cdk.CfnOutput(this, 'AlertTopicArn', {
      value: alertTopic.topicArn,
      exportName: `${tablePrefix}-AlertTopicArn`,
      description: 'SNS Topic ARN for CloudWatch alarms - subscribe email in AWS Console',
    });
  }
}

