import { Post } from '../types';

/**
 * Get all category feed posts (hardcoded for now)
 * This function returns all posts from all categories, including aggregated posts for People and Teams
 */
export function getAllCategoryFeedPosts(): Post[] {
  const now = Date.now();
  const basePosts: Record<string, Post[]> = {
    'Influencers': [
      {
        id: 'inf-1',
        userId: 'user-1',
        username: 'trading_pro',
        displayName: 'Trading Pro',
        content: '@AlixEarle just signed a massive deal with a skincare brand. Her engagement metrics are through the roof! 📈',
        entityId: 11,
        entityTicker: 'ALIX',
        entityName: 'Alix Earle',
        sentiment: 'positive',
        likes: 267,
        comments: 38,
        isLiked: false,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 12).toISOString(),
      },
      {
        id: 'inf-1b',
        userId: 'user-6',
        username: 'zuey',
        displayName: 'Zuey',
        content: 'The influencer marketing landscape is shifting. TikTok creators are getting bigger brand deals than ever before. What do you all think?',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 145,
        comments: 28,
        isLiked: false,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 45).toISOString(),
      },
      {
        id: 'inf-2',
        userId: 'user-2',
        username: 'market_watcher',
        displayName: 'Market Watcher',
        content: '@MrBeast\'s recent video didn\'t hit the same. Views are down and the engagement feels off. Maybe oversaturation?',
        entityId: 12,
        entityTicker: 'MRBST',
        entityName: 'MrBeast',
        sentiment: 'negative',
        likes: 189,
        comments: 42,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 30).toISOString(),
      },
      {
        id: 'inf-3',
        userId: 'user-3',
        username: 'social_analyst',
        displayName: 'Social Analyst',
        content: '@KaiCenat is absolutely crushing it on Kick. His stream numbers are insane and he\'s pulling in new sponsorships every week.',
        entityId: 14,
        entityTicker: 'KACEN',
        entityName: 'Kai Cenat',
        sentiment: 'positive',
        likes: 312,
        comments: 51,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 60 * 1).toISOString(),
      },
      {
        id: 'inf-4',
        userId: 'user-4',
        username: 'content_king',
        displayName: 'Content King',
        content: 'Not a good look for @LoganPaul. The recent drama is affecting his brand partnerships. @JakePaul might be the better bet right now.',
        entityId: 15,
        entityTicker: 'LPAUL',
        entityName: 'Logan Paul',
        sentiment: 'negative',
        likes: 234,
        comments: 39,
        isLiked: false,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 2).toISOString(),
      },
      {
        id: 'inf-5',
        userId: 'user-5',
        username: 'influencer_tracker',
        displayName: 'Influencer Tracker',
        content: '@EmmaChamberlain just launched her coffee brand and it\'s already sold out. The lifestyle content queen strikes again!',
        entityId: 16,
        entityTicker: 'ECHAM',
        entityName: 'Emma Chamberlain',
        sentiment: 'positive',
        likes: 298,
        comments: 45,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
      },
      {
        id: 'inf-6',
        userId: 'user-7',
        username: 'content_analyst',
        displayName: 'Content Analyst',
        content: '@AdinRoss and @KaiCenat collabing was huge. Both of their stocks went up after that stream. Smart move by both.',
        entityId: 17,
        entityTicker: 'AROSS',
        entityName: 'Adin Ross',
        sentiment: 'positive',
        likes: 356,
        comments: 62,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 60 * 4).toISOString(),
      },
      {
        id: 'inf-7',
        userId: 'user-8',
        username: 'social_media_guru',
        displayName: 'Social Media Guru',
        content: 'The shift from Instagram to TikTok for influencer marketing is real. Engagement rates are way higher on short-form video platforms.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 112,
        comments: 18,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 5).toISOString(),
      },
      {
        id: 'inf-8',
        userId: 'user-9',
        username: 'brand_deals',
        displayName: 'Brand Deals',
        content: '@CharliDAmelio\'s comeback is real. Her recent partnerships are bringing back the engagement she had during peak TikTok.',
        entityId: 20,
        entityTicker: 'CDAME',
        entityName: 'Charli D\'Amelio',
        sentiment: 'positive',
        likes: 278,
        comments: 41,
        isLiked: false,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 20).toISOString(),
      },
    ],
    'Political Figures': [
      {
        id: 'pol-1',
        userId: 'user-1',
        username: 'political_analyst',
        displayName: 'Political Analyst',
        content: '@DonaldTrump\'s rally turnout numbers are massive. The base enthusiasm is off the charts compared to previous cycles.',
        entityId: 10,
        entityTicker: 'TRUMP',
        entityName: 'Donald Trump',
        sentiment: 'positive',
        likes: 534,
        comments: 89,
        isLiked: false,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 20).toISOString(),
      },
      {
        id: 'pol-2',
        userId: 'user-2',
        username: 'election_watcher',
        displayName: 'Election Watcher',
        content: '@NikkiHaley\'s campaign is struggling to find its footing. The fundraising numbers aren\'t where they need to be.',
        entityId: 11,
        entityTicker: 'NHAL',
        entityName: 'Nikki Haley',
        sentiment: 'negative',
        likes: 234,
        comments: 45,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 45).toISOString(),
      },
      {
        id: 'pol-3',
        userId: 'user-3',
        username: 'politics_trader',
        displayName: 'Politics Trader',
        content: 'The social media engagement for @DonaldTrump is crushing everyone else. His reach is unmatched right now.',
        entityId: 10,
        entityTicker: 'TRUMP',
        entityName: 'Donald Trump',
        sentiment: 'positive',
        likes: 412,
        comments: 67,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 60 * 1).toISOString(),
      },
      {
        id: 'pol-4',
        userId: 'user-4',
        username: 'campaign_tracker',
        displayName: 'Campaign Tracker',
        content: '@GavinNewsom\'s approval ratings are taking a hit. The policy decisions aren\'t landing well with voters.',
        entityId: 12,
        entityTicker: 'GNEW',
        entityName: 'Gavin Newsom',
        sentiment: 'negative',
        likes: 189,
        comments: 38,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 2).toISOString(),
      },
      {
        id: 'pol-5',
        userId: 'user-5',
        username: 'political_insider',
        displayName: 'Political Insider',
        content: 'The debate performance by @DonaldTrump changed the whole narrative. Media coverage shifted overnight.',
        entityId: 10,
        entityTicker: 'TRUMP',
        entityName: 'Donald Trump',
        sentiment: 'positive',
        likes: 356,
        comments: 58,
        isLiked: false,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
      },
      {
        id: 'pol-6',
        userId: 'user-13',
        username: 'election_analyst',
        displayName: 'Election Analyst',
        content: 'Swing state polling shows @DonaldTrump gaining ground in key battlegrounds. The electoral map is shifting.',
        entityId: 10,
        entityTicker: 'TRUMP',
        entityName: 'Donald Trump',
        sentiment: 'positive',
        likes: 389,
        comments: 62,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 30).toISOString(),
      },
      {
        id: 'pol-7',
        userId: 'user-14',
        username: 'political_observer',
        displayName: 'Political Observer',
        content: 'The use of AI and social media in campaigns this cycle is unprecedented. Both sides are pushing boundaries.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 167,
        comments: 29,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 4).toISOString(),
      },
      {
        id: 'pol-8',
        userId: 'user-15',
        username: 'politics_tracker',
        displayName: 'Politics Tracker',
        content: '@GavinNewsom and @NikkiHaley both struggling with independent voters. The middle ground is shrinking.',
        entityId: 12,
        entityTicker: 'GNEW',
        entityName: 'Gavin Newsom',
        sentiment: 'negative',
        likes: 278,
        comments: 51,
        isLiked: false,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 5).toISOString(),
      },
    ],
    'Actors': [
      {
        id: 'actor-1',
        userId: 'user-1',
        username: 'film_critic',
        displayName: 'Film Critic',
        content: '@Zendaya just won another Emmy. Her range from Euphoria to Dune shows she\'s one of the most versatile actors working today.',
        entityId: 50,
        entityTicker: 'ZENDA',
        entityName: 'Zendaya',
        sentiment: 'positive',
        likes: 445,
        comments: 72,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 15).toISOString(),
      },
      {
        id: 'actor-2',
        userId: 'user-2',
        username: 'movie_buff',
        displayName: 'Movie Buff',
        content: '@TimothéeChalamet\'s performance in Dune 2 was incredible. He\'s becoming the face of this generation of actors.',
        entityId: 51,
        entityTicker: 'TIMCH',
        entityName: 'Timothée Chalamet',
        sentiment: 'positive',
        likes: 389,
        comments: 58,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 30).toISOString(),
      },
      {
        id: 'actor-3',
        userId: 'user-3',
        username: 'tv_watcher',
        displayName: 'TV Watcher',
        content: '@SydneySweeney is everywhere right now. Euphoria, White Lotus, and now producing her own projects. She\'s building an empire.',
        entityId: 52,
        entityTicker: 'SYDSW',
        entityName: 'Sydney Sweeney',
        sentiment: 'positive',
        likes: 356,
        comments: 61,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 45).toISOString(),
      },
      {
        id: 'actor-4',
        userId: 'user-4',
        username: 'spider_fan',
        displayName: 'Spider Fan',
        content: '@TomHolland\'s next Spider-Man movie is going to be huge. The franchise is in great hands with him.',
        entityId: 53,
        entityTicker: 'TOMHO',
        entityName: 'Tom Holland',
        sentiment: 'positive',
        likes: 512,
        comments: 89,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 20).toISOString(),
      },
      {
        id: 'actor-5',
        userId: 'user-5',
        username: 'tv_enthusiast',
        displayName: 'TV Enthusiast',
        content: '@PedroPascal is having a moment. The Last of Us, The Mandalorian, and now Gladiator 2. He\'s the most in-demand actor right now.',
        entityId: 54,
        entityTicker: 'PEDPA',
        entityName: 'Pedro Pascal',
        sentiment: 'positive',
        likes: 423,
        comments: 67,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 10).toISOString(),
      },
      {
        id: 'actor-6',
        userId: 'user-15',
        username: 'entertainment_analyst',
        displayName: 'Entertainment Analyst',
        content: 'The box office is struggling but these actors are still drawing audiences. @Zendaya, @TomHolland, and @TimothéeChalamet are the new A-list.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 234,
        comments: 42,
        isLiked: false,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 1).toISOString(),
      },
      {
        id: 'actor-7',
        userId: 'user-16',
        username: 'casting_director',
        displayName: 'Casting Director',
        content: '@SydneySweeney and @PedroPascal both have incredible range. They can do drama, comedy, action - everything. That\'s rare.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 198,
        comments: 35,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 2).toISOString(),
      },
      {
        id: 'actor-8',
        userId: 'user-17',
        username: 'film_producer',
        displayName: 'Film Producer',
        content: 'Studios are betting big on @Zendaya and @TimothéeChalamet. They\'re the future of Hollywood. Smart investments.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 267,
        comments: 48,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
      },
    ],
    'NBA Players': [
      {
        id: 'nba-1',
        userId: 'user-1',
        username: 'nba_analyst',
        displayName: 'NBA Analyst',
        content: '@LeBronJames is still playing at an elite level in year 21. The longevity is unmatched. GOAT conversation is real.',
        entityId: 55,
        entityTicker: 'LEBRJ',
        entityName: 'LeBron James',
        sentiment: 'positive',
        likes: 523,
        comments: 89,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 12).toISOString(),
      },
      {
        id: 'nba-2',
        userId: 'user-2',
        username: 'warriors_fan',
        displayName: 'Warriors Fan',
        content: '@StephenCurry just hit another game-winner. The man is clutch. Warriors are back in championship form.',
        entityId: 56,
        entityTicker: 'STCUR',
        entityName: 'Stephen Curry',
        sentiment: 'positive',
        likes: 467,
        comments: 76,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 25).toISOString(),
      },
      {
        id: 'nba-3',
        userId: 'user-3',
        username: 'spurs_fan',
        displayName: 'Spurs Fan',
        content: '@VictorWembanyama is a generational talent. The defense, the shooting, the passing - he\'s the real deal. Future MVP.',
        entityId: 57,
        entityTicker: 'VICWE',
        entityName: 'Victor Wembanyama',
        sentiment: 'positive',
        likes: 389,
        comments: 64,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 35).toISOString(),
      },
      {
        id: 'nba-4',
        userId: 'user-4',
        username: 'nuggets_fan',
        displayName: 'Nuggets Fan',
        content: '@NikolaJokic is the best passing big man ever. The vision is incredible. Another triple-double tonight.',
        entityId: 58,
        entityTicker: 'NIKJO',
        entityName: 'Nikola Jokic',
        sentiment: 'positive',
        likes: 445,
        comments: 72,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 18).toISOString(),
      },
      {
        id: 'nba-5',
        userId: 'user-5',
        username: 'mavs_fan',
        displayName: 'Mavs Fan',
        content: '@LukaDoncic dropped 50 tonight. The step-back threes are automatic. He\'s carrying the Mavs to the playoffs.',
        entityId: 59,
        entityTicker: 'LUKDO',
        entityName: 'Luka Dončić',
        sentiment: 'positive',
        likes: 512,
        comments: 91,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 8).toISOString(),
      },
      {
        id: 'nba-6',
        userId: 'user-15',
        username: 'wolves_fan',
        displayName: 'Wolves Fan',
        content: '@AnthonyEdwards is the future of the league. The athleticism and scoring ability is off the charts. All-Star bound.',
        entityId: 60,
        entityTicker: 'ANTED',
        entityName: 'Anthony Edwards',
        sentiment: 'positive',
        likes: 356,
        comments: 58,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 42).toISOString(),
      },
      {
        id: 'nba-7',
        userId: 'user-16',
        username: 'thunder_fan',
        displayName: 'Thunder Fan',
        content: '@ShaiGilgeousAlexander is having an MVP-caliber season. The scoring, the efficiency, the leadership. Thunder are building something special.',
        entityId: 61,
        entityTicker: 'SHGIL',
        entityName: 'Shai Gilgeous-Alexander',
        sentiment: 'positive',
        likes: 423,
        comments: 67,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 28).toISOString(),
      },
      {
        id: 'nba-8',
        userId: 'user-17',
        username: 'basketball_expert',
        displayName: 'Basketball Expert',
        content: 'The league is stacked with talent. @LeBronJames, @StephenCurry, @LukaDoncic, @NikolaJokic - we\'re witnessing greatness.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 278,
        comments: 45,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 60 * 1).toISOString(),
      },
      {
        id: 'nba-9',
        userId: 'user-18',
        username: 'draft_analyst',
        displayName: 'Draft Analyst',
        content: '@VictorWembanyama and @AnthonyEdwards represent the new generation. The future of the NBA is in good hands.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 234,
        comments: 38,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 2).toISOString(),
      },
    ],
    'NFL Players': [
      {
        id: 'nfl-1',
        userId: 'user-1',
        username: 'chiefs_fan',
        displayName: 'Chiefs Fan',
        content: '@PatrickMahomes is the best quarterback in the league. The arm talent and clutch factor is unmatched. Another Super Bowl run incoming.',
        entityId: 62,
        entityTicker: 'PATMA',
        entityName: 'Patrick Mahomes',
        sentiment: 'positive',
        likes: 567,
        comments: 94,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 10).toISOString(),
      },
      {
        id: 'nfl-2',
        userId: 'user-2',
        username: 'draft_expert',
        displayName: 'Draft Expert',
        content: '@DrakeMaye has all the tools to be a franchise QB. The arm strength and mobility combo is rare. Top 5 pick for sure.',
        entityId: 63,
        entityTicker: 'DRAMA',
        entityName: 'Drake Maye',
        sentiment: 'positive',
        likes: 312,
        comments: 52,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 30).toISOString(),
      },
      {
        id: 'nfl-3',
        userId: 'user-3',
        username: 'bengals_fan',
        displayName: 'Bengals Fan',
        content: '@JoeBurrow is back and looking sharp. The accuracy and decision-making is elite. Bengals are Super Bowl contenders again.',
        entityId: 64,
        entityTicker: 'JOEBU',
        entityName: 'Joe Burrow',
        sentiment: 'positive',
        likes: 489,
        comments: 78,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 15).toISOString(),
      },
      {
        id: 'nfl-4',
        userId: 'user-4',
        username: 'tight_end_fan',
        displayName: 'Tight End Fan',
        content: '@TravisKelce is still the best tight end in football. The chemistry with Mahomes is unreal. Record-breaking season incoming.',
        entityId: 65,
        entityTicker: 'TRAKE',
        entityName: 'Travis Kelce',
        sentiment: 'positive',
        likes: 445,
        comments: 71,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 22).toISOString(),
      },
      {
        id: 'nfl-5',
        userId: 'user-5',
        username: 'college_football_fan',
        displayName: 'College Football Fan',
        content: '@CalebWilliams is the most NFL-ready QB in the draft. The playmaking ability and arm talent will translate immediately.',
        entityId: 66,
        entityTicker: 'CALWI',
        entityName: 'Caleb Williams',
        sentiment: 'positive',
        likes: 378,
        comments: 63,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 18).toISOString(),
      },
      {
        id: 'nfl-6',
        userId: 'user-15',
        username: 'nfl_analyst',
        displayName: 'NFL Analyst',
        content: 'The quarterback position is stacked. @PatrickMahomes, @JoeBurrow, and the next generation with @CalebWilliams and @DrakeMaye.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 234,
        comments: 41,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 60 * 1).toISOString(),
      },
      {
        id: 'nfl-7',
        userId: 'user-16',
        username: 'fantasy_expert',
        displayName: 'Fantasy Expert',
        content: '@TravisKelce and @PatrickMahomes connection is automatic. Best QB-TE duo in NFL history. Fantasy gold.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 267,
        comments: 45,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 2).toISOString(),
      },
      {
        id: 'nfl-8',
        userId: 'user-17',
        username: 'draft_scout',
        displayName: 'Draft Scout',
        content: 'This QB class is special. @CalebWilliams and @DrakeMaye both have franchise-changing potential. Teams are going to be aggressive.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 198,
        comments: 34,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
      },
      {
        id: 'nfl-9',
        userId: 'user-18',
        username: 'goat_debate',
        displayName: 'GOAT Debate',
        content: '@People @TomBrady is the greatest quarterback of all time. 7 Super Bowls, 5 MVPs, 20+ seasons. The GOAT debate is over.',
        entityId: 69,
        entityTicker: 'TOMBR',
        entityName: 'Tom Brady',
        sentiment: 'positive',
        likes: 512,
        comments: 89,
        isLiked: true,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 5).toISOString(),
      },
    ],
    'Soccer Players': [
      {
        id: 'soccer-1',
        userId: 'user-1',
        username: 'messi_fan',
        displayName: 'Messi Fan',
        content: '@LionelMessi is still the GOAT. The World Cup win sealed it. The vision, the passing, the goals - he\'s unmatched.',
        entityId: 67,
        entityTicker: 'LIOME',
        entityName: 'Lionel Messi',
        sentiment: 'positive',
        likes: 623,
        comments: 112,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 8).toISOString(),
      },
      {
        id: 'soccer-2',
        userId: 'user-2',
        username: 'ronaldo_fan',
        displayName: 'Ronaldo Fan',
        content: '@CristianoRonaldo is a goal-scoring machine. The longevity and consistency is incredible. Still breaking records at his age.',
        entityId: 68,
        entityTicker: 'CRIRO',
        entityName: 'Cristiano Ronaldo',
        sentiment: 'positive',
        likes: 589,
        comments: 98,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 12).toISOString(),
      },
      {
        id: 'soccer-3',
        userId: 'user-3',
        username: 'football_analyst',
        displayName: 'Football Analyst',
        content: 'The Messi vs Ronaldo debate will never end. Both are legends. @LionelMessi has the World Cup, @CristianoRonaldo has the longevity. Both GOATs.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 445,
        comments: 156,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 25).toISOString(),
      },
      {
        id: 'soccer-4',
        userId: 'user-4',
        username: 'soccer_enthusiast',
        displayName: 'Soccer Enthusiast',
        content: '@LionelMessi\'s move to Inter Miami changed MLS forever. The impact on American soccer is massive. Attendance records everywhere.',
        entityId: 67,
        entityTicker: 'LIOME',
        entityName: 'Lionel Messi',
        sentiment: 'positive',
        likes: 512,
        comments: 87,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 18).toISOString(),
      },
      {
        id: 'soccer-5',
        userId: 'user-5',
        username: 'global_football_fan',
        displayName: 'Global Football Fan',
        content: '@CristianoRonaldo in Saudi Arabia is still putting up insane numbers. The man is a machine. Age is just a number for him.',
        entityId: 68,
        entityTicker: 'CRIRO',
        entityName: 'Cristiano Ronaldo',
        sentiment: 'positive',
        likes: 467,
        comments: 76,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 30).toISOString(),
      },
      {
        id: 'soccer-6',
        userId: 'user-15',
        username: 'world_cup_fan',
        displayName: 'World Cup Fan',
        content: 'Messi finally got his World Cup. The greatest player of all time deserved it. @LionelMessi\'s legacy is complete.',
        entityId: 67,
        entityTicker: 'LIOME',
        entityName: 'Lionel Messi',
        sentiment: 'positive',
        likes: 556,
        comments: 94,
        isLiked: true,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 40).toISOString(),
      },
      {
        id: 'soccer-7',
        userId: 'user-16',
        username: 'champions_league_fan',
        displayName: 'Champions League Fan',
        content: 'Ronaldo\'s Champions League record is untouchable. @CristianoRonaldo has 5 UCL titles and the most goals. Legendary.',
        entityId: 68,
        entityTicker: 'CRIRO',
        entityName: 'Cristiano Ronaldo',
        sentiment: 'positive',
        likes: 489,
        comments: 82,
        isLiked: false,
        isBookmarked: true,
        timestamp: new Date(now - 1000 * 60 * 22).toISOString(),
      },
      {
        id: 'soccer-8',
        userId: 'user-17',
        username: 'football_historian',
        displayName: 'Football Historian',
        content: 'We\'re witnessing the end of an era. @LionelMessi and @CristianoRonaldo defined football for 15+ years. Two of the greatest ever.',
        entityId: undefined,
        entityTicker: undefined,
        entityName: undefined,
        sentiment: undefined,
        likes: 378,
        comments: 134,
        isLiked: true,
        isBookmarked: false,
        timestamp: new Date(now - 1000 * 60 * 60 * 1).toISOString(),
      },
    ],
    'NFL Teams': [],
    'NBA Teams': [],
    'College Basketball Teams': [],
    'Teams': [],
    'Hip Hop': [],
    'Country Music': [],
    'Pop Music': [],
    'People': [],
  };

  // Aggregate all posts from People subcategories
  const peopleSubcategories = [
    'Actors',
    'NBA Players',
    'NFL Players',
    'Soccer Players',
    'Influencers',
    'Political Figures',
    'Hip Hop',
    'Country Music',
    'Pop Music',
  ];
  const peoplePosts: Post[] = [];
  peopleSubcategories.forEach(subcategory => {
    const subcategoryPosts = basePosts[subcategory] || [];
    peoplePosts.push(...subcategoryPosts);
  });

  // Aggregate all posts from Teams subcategories
  const teamsSubcategories = [
    'NFL Teams',
    'NBA Teams',
    'College Basketball Teams',
  ];
  const teamsPosts: Post[] = [];
  teamsSubcategories.forEach(subcategory => {
    const subcategoryPosts = basePosts[subcategory] || [];
    teamsPosts.push(...subcategoryPosts);
  });

  // Combine all posts from all categories
  const allPosts: Post[] = [];
  Object.values(basePosts).forEach(categoryPosts => {
    allPosts.push(...categoryPosts);
  });
  allPosts.push(...peoplePosts); // Add aggregated People posts
  allPosts.push(...teamsPosts); // Add aggregated Teams posts

  return allPosts;
}
