/**
 * Centralized Entity Data
 * This ensures consistent entity information across all screens
 */

export interface EntityData {
  id: number;
  ticker: string;
  name: string;
  category: string;
  basePrice: number;
  description: string;
}

// Single source of truth for all entities
export const ENTITIES: EntityData[] = [
  {
    id: 10,
    ticker: 'TRUMP',
    name: 'Donald Trump',
    category: 'Political Figures',
    basePrice: 142.55,
    description: 'Former president and political figure. Trade confidence in political influence and electoral prospects.',
  },
  // Influencers
  {
    id: 11,
    ticker: 'ALIX',
    name: 'Alix Earle',
    category: 'Influencers',
    basePrice: 200.47,
    description: 'TikTok influencer and content creator. Track confidence in Alix Earle\'s influence, brand partnerships, and audience growth.',
  },
  {
    id: 12,
    ticker: 'MRBST',
    name: 'MrBeast',
    category: 'Influencers',
    basePrice: 195.83,
    description: 'YouTube creator and philanthropist. Trade confidence in MrBeast\'s channel growth, business ventures, and social impact initiatives.',
  },
  {
    id: 14,
    ticker: 'KACEN',
    name: 'Kai Cenat',
    category: 'Influencers',
    basePrice: 185.29,
    description: 'Twitch streamer and content creator. Trade confidence in Kai Cenat\'s streaming success, audience engagement, and career trajectory.',
  },
  {
    id: 20,
    ticker: 'CDAME',
    name: 'Charli D\'Amelio',
    category: 'Influencers',
    basePrice: 182.56,
    description: 'TikTok star and social media influencer. Trade confidence in Charli D\'Amelio\'s influence, brand deals, and career growth.',
  },
  {
    id: 15,
    ticker: 'LPAUL',
    name: 'Logan Paul',
    category: 'Influencers',
    basePrice: 178.91,
    description: 'YouTube creator, boxer, and entrepreneur. Track confidence in Logan Paul\'s ventures, fight career, and business success.',
  },
  {
    id: 19,
    ticker: 'JPAUL',
    name: 'Jake Paul',
    category: 'Influencers',
    basePrice: 175.34,
    description: 'YouTube creator, boxer, and entrepreneur. Track confidence in Jake Paul\'s boxing career, business ventures, and public profile.',
  },
  {
    id: 18,
    ticker: 'ACOOP',
    name: 'Alex Cooper',
    category: 'Influencers',
    basePrice: 172.68,
    description: 'Podcast host and media personality. Trade confidence in Alex Cooper\'s podcast success, brand expansion, and media influence.',
  },
  {
    id: 16,
    ticker: 'ECHAM',
    name: 'Emma Chamberlain',
    category: 'Influencers',
    basePrice: 162.42,
    description: 'YouTube creator and fashion influencer. Trade confidence in Emma Chamberlain\'s brand partnerships, content creation, and influence.',
  },
  {
    id: 17,
    ticker: 'AROSS',
    name: 'Adin Ross',
    category: 'Influencers',
    basePrice: 145.76,
    description: 'Twitch streamer and content creator. Track confidence in Adin Ross\'s streaming career, collaborations, and audience growth.',
  },
  {
    id: 13,
    ticker: 'ATATE',
    name: 'Andrew Tate',
    category: 'Influencers',
    basePrice: 128.13,
    description: 'Controversial internet personality and former kickboxer. Track confidence in Andrew Tate\'s influence and media presence.',
  },
  // Music Artists
  {
    id: 21,
    ticker: 'TSWFT',
    name: 'Taylor Swift',
    category: 'Music Artists',
    basePrice: 198.64,
    description: 'Award-winning singer-songwriter and global pop icon. Track confidence in Taylor Swift\'s album releases, tours, and cultural influence.',
  },
  {
    id: 22,
    ticker: 'DRAKE',
    name: 'Drake',
    category: 'Music Artists',
    basePrice: 192.37,
    description: 'Grammy-winning rapper and record producer. Trade confidence in Drake\'s chart dominance, album releases, and business ventures.',
  },
  {
    id: 23,
    ticker: 'KANYE',
    name: 'Kanye West',
    category: 'Music Artists',
    basePrice: 186.52,
    description: 'Influential rapper, producer, and fashion designer. Track confidence in Kanye West\'s music releases and brand partnerships.',
  },
  {
    id: 24,
    ticker: 'BUNNY',
    name: 'Bad Bunny',
    category: 'Music Artists',
    basePrice: 181.79,
    description: 'Global reggaeton and Latin trap artist. Trade confidence in Bad Bunny\'s chart success, tours, and cultural impact.',
  },
  {
    id: 25,
    ticker: 'TSOTT',
    name: 'Travis Scott',
    category: 'Music Artists',
    basePrice: 177.23,
    description: 'Hip-hop artist and record producer. Track confidence in Travis Scott\'s album releases, collaborations, and live performances.',
  },
  {
    id: 26,
    ticker: 'RODRI',
    name: 'Olivia Rodrigo',
    category: 'Music Artists',
    basePrice: 173.86,
    description: 'Rising pop star and songwriter. Trade confidence in Olivia Rodrigo\'s album success, chart performance, and growing fanbase.',
  },
  {
    id: 27,
    ticker: 'CARTI',
    name: 'Playboi Carti',
    category: 'Music Artists',
    basePrice: 169.41,
    description: 'Rapper and songwriter known for experimental sound. Track confidence in Playboi Carti\'s releases and influence on hip-hop culture.',
  },
  {
    id: 28,
    ticker: 'ISPCE',
    name: 'Ice Spice',
    category: 'Music Artists',
    basePrice: 165.98,
    description: 'Rising rapper and viral sensation. Trade confidence in Ice Spice\'s chart success, collaborations, and career growth.',
  },
  {
    id: 29,
    ticker: 'WKEND',
    name: 'The Weeknd',
    category: 'Music Artists',
    basePrice: 162.54,
    description: 'Grammy-winning singer, songwriter, and producer. Track confidence in The Weeknd\'s album releases, tours, and artistic evolution.',
  },
  {
    id: 30,
    ticker: 'DOJAC',
    name: 'Doja Cat',
    category: 'Music Artists',
    basePrice: 159.27,
    description: 'Singer, rapper, and songwriter. Trade confidence in Doja Cat\'s chart-topping hits, album releases, and social media presence.',
  },
  // Political Figures
  {
    id: 31,
    ticker: 'JBIDN',
    name: 'Joe Biden',
    category: 'Political Figures',
    basePrice: 141.23,
    description: 'Current president of the United States. Track confidence in Joe Biden\'s policy decisions, approval ratings, and political influence.',
  },
  {
    id: 32,
    ticker: 'KHARR',
    name: 'Kamala Harris',
    category: 'Political Figures',
    basePrice: 138.67,
    description: 'Vice President of the United States. Trade confidence in Kamala Harris\'s political standing, policy impact, and future prospects.',
  },
  {
    id: 33,
    ticker: 'RDESA',
    name: 'Ron DeSantis',
    category: 'Political Figures',
    basePrice: 135.89,
    description: 'Governor of Florida and political figure. Track confidence in Ron DeSantis\'s political influence, policy decisions, and electoral prospects.',
  },
  {
    id: 34,
    ticker: 'AOC',
    name: 'Alexandria Ocasio-Cortez',
    category: 'Political Figures',
    basePrice: 133.42,
    description: 'U.S. Representative and progressive political figure. Trade confidence in Alexandria Ocasio-Cortez\'s policy advocacy and political influence.',
  },
  {
    id: 35,
    ticker: 'VRAMA',
    name: 'Vivek Ramaswamy',
    category: 'Political Figures',
    basePrice: 130.76,
    description: 'Entrepreneur and political figure. Track confidence in Vivek Ramaswamy\'s political influence, policy positions, and public profile.',
  },
  {
    id: 36,
    ticker: 'NHALE',
    name: 'Nikki Haley',
    category: 'Political Figures',
    basePrice: 128.54,
    description: 'Former U.N. Ambassador and political figure. Trade confidence in Nikki Haley\'s political standing, policy influence, and electoral prospects.',
  },
  {
    id: 37,
    ticker: 'GNEWS',
    name: 'Gavin Newsom',
    category: 'Political Figures',
    basePrice: 126.18,
    description: 'Governor of California and political figure. Track confidence in Gavin Newsom\'s policy decisions, political influence, and future prospects.',
  },
  {
    id: 38,
    ticker: 'TCARS',
    name: 'Tucker Carlson',
    category: 'Political Figures',
    basePrice: 123.91,
    description: 'Media personality and political commentator. Trade confidence in Tucker Carlson\'s influence, media presence, and political impact.',
  },
  {
    id: 39,
    ticker: 'BSAND',
    name: 'Bernie Sanders',
    category: 'Political Figures',
    basePrice: 121.45,
    description: 'U.S. Senator and progressive political figure. Track confidence in Bernie Sanders\'s policy advocacy, political influence, and public support.',
  },
  // Actors
  {
    id: 50,
    ticker: 'ZENDA',
    name: 'Zendaya',
    category: 'Actors',
    basePrice: 195.50,
    description: 'Award-winning actress and singer. Trade confidence in Zendaya\'s acting career, box office success, and industry influence.',
  },
  {
    id: 51,
    ticker: 'TIMCH',
    name: 'Timothée Chalamet',
    category: 'Actors',
    basePrice: 188.75,
    description: 'Acclaimed actor known for dramatic roles. Track confidence in Timothée Chalamet\'s film projects, awards recognition, and career trajectory.',
  },
  {
    id: 52,
    ticker: 'SYDSW',
    name: 'Sydney Sweeney',
    category: 'Actors',
    basePrice: 182.30,
    description: 'Rising actress and producer. Trade confidence in Sydney Sweeney\'s acting roles, production ventures, and industry presence.',
  },
  {
    id: 53,
    ticker: 'TOMHO',
    name: 'Tom Holland',
    category: 'Actors',
    basePrice: 190.25,
    description: 'Actor best known for Spider-Man franchise. Track confidence in Tom Holland\'s film projects, box office performance, and career growth.',
  },
  {
    id: 54,
    ticker: 'PEDPA',
    name: 'Pedro Pascal',
    category: 'Actors',
    basePrice: 185.90,
    description: 'Versatile actor in film and television. Trade confidence in Pedro Pascal\'s roles, show success, and entertainment industry impact.',
  },
  // NBA Players
  {
    id: 55,
    ticker: 'LEBRJ',
    name: 'LeBron James',
    category: 'NBA Players',
    basePrice: 250.00,
    description: 'NBA superstar and all-time great. Trade confidence in LeBron James\'s performance, team success, and legacy in basketball.',
  },
  {
    id: 56,
    ticker: 'STCUR',
    name: 'Stephen Curry',
    category: 'NBA Players',
    basePrice: 245.50,
    description: 'Three-point shooting legend and Warriors icon. Track confidence in Stephen Curry\'s shooting, team performance, and career milestones.',
  },
  {
    id: 57,
    ticker: 'VICWE',
    name: 'Victor Wembanyama',
    category: 'NBA Players',
    basePrice: 220.75,
    description: 'Rising star and generational talent. Trade confidence in Victor Wembanyama\'s development, rookie performance, and future potential.',
  },
  {
    id: 58,
    ticker: 'NIKJO',
    name: 'Nikola Jokic',
    category: 'NBA Players',
    basePrice: 240.25,
    description: 'Reigning MVP and elite center. Track confidence in Nikola Jokic\'s playmaking, team success, and championship aspirations.',
  },
  {
    id: 59,
    ticker: 'LUKDO',
    name: 'Luka Dončić',
    category: 'NBA Players',
    basePrice: 235.90,
    description: 'Dynamic guard and triple-double machine. Trade confidence in Luka Dončić\'s scoring, assists, and Mavericks success.',
  },
  {
    id: 60,
    ticker: 'ANTED',
    name: 'Anthony Edwards',
    category: 'NBA Players',
    basePrice: 215.30,
    description: 'Explosive guard and rising star. Track confidence in Anthony Edwards\'s scoring ability, team leadership, and playoff performance.',
  },
  {
    id: 61,
    ticker: 'SHGIL',
    name: 'Shai Gilgeous-Alexander',
    category: 'NBA Players',
    basePrice: 230.60,
    description: 'Elite guard and Thunder leader. Trade confidence in Shai Gilgeous-Alexander\'s scoring, team building, and All-Star status.',
  },
  // NFL Players
  {
    id: 62,
    ticker: 'PATMA',
    name: 'Patrick Mahomes',
    category: 'NFL Players',
    basePrice: 255.00,
    description: 'Super Bowl champion quarterback and Chiefs leader. Trade confidence in Patrick Mahomes\'s performance, team success, and MVP potential.',
  },
  {
    id: 63,
    ticker: 'DRAMA',
    name: 'Drake Maye',
    category: 'NFL Players',
    basePrice: 200.50,
    description: 'Rising quarterback prospect. Track confidence in Drake Maye\'s development, draft position, and NFL career trajectory.',
  },
  {
    id: 64,
    ticker: 'JOEBU',
    name: 'Joe Burrow',
    category: 'NFL Players',
    basePrice: 245.75,
    description: 'Elite quarterback and Bengals leader. Trade confidence in Joe Burrow\'s passing, playoff performance, and championship aspirations.',
  },
  {
    id: 65,
    ticker: 'TRAKE',
    name: 'Travis Kelce',
    category: 'NFL Players',
    basePrice: 235.25,
    description: 'All-Pro tight end and Chiefs star. Track confidence in Travis Kelce\'s receiving, team chemistry, and Super Bowl success.',
  },
  {
    id: 66,
    ticker: 'CALWI',
    name: 'Caleb Williams',
    category: 'NFL Players',
    basePrice: 210.90,
    description: 'Top quarterback prospect and Heisman winner. Trade confidence in Caleb Williams\'s draft stock, NFL readiness, and future potential.',
  },
  {
    id: 69,
    ticker: 'TOMBR',
    name: 'Tom Brady',
    category: 'NFL Players',
    basePrice: 250.00,
    description: 'Seven-time Super Bowl champion and greatest quarterback of all time. Trade confidence in Tom Brady\'s legacy, retirement impact, and post-career ventures.',
  },
  // Soccer Players
  {
    id: 67,
    ticker: 'LIOME',
    name: 'Lionel Messi',
    category: 'Soccer Players',
    basePrice: 260.00,
    description: 'World Cup champion and football legend. Trade confidence in Lionel Messi\'s performance, team success, and legacy in soccer.',
  },
  {
    id: 68,
    ticker: 'CRIRO',
    name: 'Cristiano Ronaldo',
    category: 'Soccer Players',
    basePrice: 258.50,
    description: 'Global football icon and goal-scoring machine. Track confidence in Cristiano Ronaldo\'s goals, team impact, and career milestones.',
  },
  // NFL Teams
  {
    id: 100,
    ticker: 'KCCHI',
    name: 'Kansas City Chiefs',
    category: 'NFL Teams',
    basePrice: 185.42,
    description: 'NFL team based in Kansas City. Track confidence in the Chiefs\' performance, playoff prospects, and fan engagement.',
  },
  {
    id: 101,
    ticker: 'BUFBI',
    name: 'Buffalo Bills',
    category: 'NFL Teams',
    basePrice: 178.93,
    description: 'NFL team based in Buffalo. Trade confidence in the Bills\' season performance, playoff chances, and team success.',
  },
  {
    id: 102,
    ticker: 'BALRA',
    name: 'Baltimore Ravens',
    category: 'NFL Teams',
    basePrice: 176.58,
    description: 'NFL team based in Baltimore. Track confidence in the Ravens\' performance, roster strength, and championship potential.',
  },
  {
    id: 103,
    ticker: 'CINBE',
    name: 'Cincinnati Bengals',
    category: 'NFL Teams',
    basePrice: 174.21,
    description: 'NFL team based in Cincinnati. Trade confidence in the Bengals\' season outlook, player performance, and playoff aspirations.',
  },
  {
    id: 104,
    ticker: 'CLEBR',
    name: 'Cleveland Browns',
    category: 'NFL Teams',
    basePrice: 165.87,
    description: 'NFL team based in Cleveland. Track confidence in the Browns\' performance, roster decisions, and season success.',
  },
  {
    id: 105,
    ticker: 'PITST',
    name: 'Pittsburgh Steelers',
    category: 'NFL Teams',
    basePrice: 172.45,
    description: 'NFL team based in Pittsburgh. Trade confidence in the Steelers\' tradition, team performance, and playoff chances.',
  },
  {
    id: 106,
    ticker: 'HOUTE',
    name: 'Houston Texans',
    category: 'NFL Teams',
    basePrice: 158.32,
    description: 'NFL team based in Houston. Track confidence in the Texans\' rebuilding process, draft picks, and future success.',
  },
  {
    id: 107,
    ticker: 'INDCO',
    name: 'Indianapolis Colts',
    category: 'NFL Teams',
    basePrice: 163.79,
    description: 'NFL team based in Indianapolis. Trade confidence in the Colts\' performance, quarterback situation, and season outlook.',
  },
  {
    id: 108,
    ticker: 'JAXJA',
    name: 'Jacksonville Jaguars',
    category: 'NFL Teams',
    basePrice: 161.24,
    description: 'NFL team based in Jacksonville. Track confidence in the Jaguars\' development, young talent, and competitive progress.',
  },
  {
    id: 109,
    ticker: 'TENTI',
    name: 'Tennessee Titans',
    category: 'NFL Teams',
    basePrice: 159.68,
    description: 'NFL team based in Tennessee. Trade confidence in the Titans\' performance, coaching decisions, and playoff potential.',
  },
  {
    id: 110,
    ticker: 'DENBR',
    name: 'Denver Broncos',
    category: 'NFL Teams',
    basePrice: 162.15,
    description: 'NFL team based in Denver. Track confidence in the Broncos\' roster moves, quarterback play, and season performance.',
  },
  {
    id: 111,
    ticker: 'LACCH',
    name: 'Los Angeles Chargers',
    category: 'NFL Teams',
    basePrice: 170.56,
    description: 'NFL team based in Los Angeles. Trade confidence in the Chargers\' talent, playoff chances, and championship aspirations.',
  },
  {
    id: 112,
    ticker: 'LARAM',
    name: 'Los Angeles Rams',
    category: 'NFL Teams',
    basePrice: 168.92,
    description: 'NFL team based in Los Angeles. Track confidence in the Rams\' roster construction, coaching, and competitive success.',
  },
  {
    id: 113,
    ticker: 'OAKRA',
    name: 'Las Vegas Raiders',
    category: 'NFL Teams',
    basePrice: 164.38,
    description: 'NFL team based in Las Vegas. Trade confidence in the Raiders\' performance, team culture, and playoff prospects.',
  },
  {
    id: 114,
    ticker: 'DALCO',
    name: 'Dallas Cowboys',
    category: 'NFL Teams',
    basePrice: 182.67,
    description: 'NFL team based in Dallas. Track confidence in the Cowboys\' performance, playoff success, and championship potential.',
  },
  {
    id: 115,
    ticker: 'NYGIA',
    name: 'New York Giants',
    category: 'NFL Teams',
    basePrice: 157.43,
    description: 'NFL team based in New York. Trade confidence in the Giants\' rebuilding efforts, draft strategy, and future success.',
  },
  {
    id: 116,
    ticker: 'PHIEA',
    name: 'Philadelphia Eagles',
    category: 'NFL Teams',
    basePrice: 180.34,
    description: 'NFL team based in Philadelphia. Track confidence in the Eagles\' performance, roster depth, and Super Bowl chances.',
  },
  {
    id: 117,
    ticker: 'WASCO',
    name: 'Washington Commanders',
    category: 'NFL Teams',
    basePrice: 155.89,
    description: 'NFL team based in Washington. Trade confidence in the Commanders\' rebuild, new ownership, and team development.',
  },
  {
    id: 118,
    ticker: 'CHIBE',
    name: 'Chicago Bears',
    category: 'NFL Teams',
    basePrice: 160.12,
    description: 'NFL team based in Chicago. Track confidence in the Bears\' quarterback development, roster building, and competitive progress.',
  },
  {
    id: 119,
    ticker: 'DETLI',
    name: 'Detroit Lions',
    category: 'NFL Teams',
    basePrice: 173.56,
    description: 'NFL team based in Detroit. Trade confidence in the Lions\' resurgence, coaching success, and playoff performance.',
  },
  {
    id: 120,
    ticker: 'GBPA',
    name: 'Green Bay Packers',
    category: 'NFL Teams',
    basePrice: 177.89,
    description: 'NFL team based in Green Bay. Track confidence in the Packers\' quarterback transition, team performance, and playoff chances.',
  },
  {
    id: 121,
    ticker: 'MINVI',
    name: 'Minnesota Vikings',
    category: 'NFL Teams',
    basePrice: 166.78,
    description: 'NFL team based in Minnesota. Trade confidence in the Vikings\' performance, roster decisions, and competitive success.',
  },
  {
    id: 122,
    ticker: 'ATLFA',
    name: 'Atlanta Falcons',
    category: 'NFL Teams',
    basePrice: 158.91,
    description: 'NFL team based in Atlanta. Track confidence in the Falcons\' rebuild, quarterback situation, and future prospects.',
  },
  {
    id: 123,
    ticker: 'CARPA',
    name: 'Carolina Panthers',
    category: 'NFL Teams',
    basePrice: 152.34,
    description: 'NFL team based in Carolina. Trade confidence in the Panthers\' rebuilding process, draft picks, and team development.',
  },
  {
    id: 124,
    ticker: 'NOSAI',
    name: 'New Orleans Saints',
    category: 'NFL Teams',
    basePrice: 167.45,
    description: 'NFL team based in New Orleans. Track confidence in the Saints\' performance, roster management, and playoff aspirations.',
  },
  {
    id: 125,
    ticker: 'TABUC',
    name: 'Tampa Bay Buccaneers',
    category: 'NFL Teams',
    basePrice: 171.23,
    description: 'NFL team based in Tampa Bay. Trade confidence in the Buccaneers\' performance, quarterback situation, and competitive success.',
  },
  {
    id: 126,
    ticker: 'ARICA',
    name: 'Arizona Cardinals',
    category: 'NFL Teams',
    basePrice: 154.67,
    description: 'NFL team based in Arizona. Track confidence in the Cardinals\' rebuild, draft strategy, and future development.',
  },
  {
    id: 127,
    ticker: 'SF49',
    name: 'San Francisco 49ers',
    category: 'NFL Teams',
    basePrice: 179.56,
    description: 'NFL team based in San Francisco. Trade confidence in the 49ers\' roster talent, coaching, and Super Bowl potential.',
  },
  {
    id: 128,
    ticker: 'SEAHA',
    name: 'Seattle Seahawks',
    category: 'NFL Teams',
    basePrice: 169.78,
    description: 'NFL team based in Seattle. Track confidence in the Seahawks\' performance, quarterback play, and playoff chances.',
  },
  {
    id: 129,
    ticker: 'NEAT',
    name: 'New England Patriots',
    category: 'NFL Teams',
    basePrice: 163.12,
    description: 'NFL team based in New England. Trade confidence in the Patriots\' rebuild, coaching decisions, and future success.',
  },
  {
    id: 130,
    ticker: 'NYJE',
    name: 'New York Jets',
    category: 'NFL Teams',
    basePrice: 165.89,
    description: 'NFL team based in New York. Track confidence in the Jets\' quarterback situation, roster talent, and competitive progress.',
  },
  {
    id: 131,
    ticker: 'MIAOL',
    name: 'Miami Dolphins',
    category: 'NFL Teams',
    basePrice: 175.34,
    description: 'NFL team based in Miami. Trade confidence in the Dolphins\' offensive performance, playoff chances, and team success.',
  },
  // NBA Teams
  {
    id: 200,
    ticker: 'BOSCE',
    name: 'Boston Celtics',
    category: 'NBA Teams',
    basePrice: 195.42,
    description: 'NBA team based in Boston. Track confidence in the Celtics\' performance, playoff prospects, and championship potential.',
  },
  {
    id: 201,
    ticker: 'MILBU',
    name: 'Milwaukee Bucks',
    category: 'NBA Teams',
    basePrice: 192.67,
    description: 'NBA team based in Milwaukee. Trade confidence in the Bucks\' roster talent, star players, and title chances.',
  },
  {
    id: 202,
    ticker: 'DENNU',
    name: 'Denver Nuggets',
    category: 'NBA Teams',
    basePrice: 190.34,
    description: 'NBA team based in Denver. Track confidence in the Nuggets\' championship core, coaching, and competitive success.',
  },
  {
    id: 203,
    ticker: 'PHOEN',
    name: 'Phoenix Suns',
    category: 'NBA Teams',
    basePrice: 188.56,
    description: 'NBA team based in Phoenix. Trade confidence in the Suns\' star power, roster depth, and playoff performance.',
  },
  {
    id: 204,
    ticker: 'LALAK',
    name: 'Los Angeles Lakers',
    category: 'NBA Teams',
    basePrice: 186.93,
    description: 'NBA team based in Los Angeles. Track confidence in the Lakers\' legacy, star players, and championship aspirations.',
  },
  {
    id: 205,
    ticker: 'GSWAR',
    name: 'Golden State Warriors',
    category: 'NBA Teams',
    basePrice: 184.78,
    description: 'NBA team based in San Francisco. Trade confidence in the Warriors\' dynasty, shooting, and title contention.',
  },
  {
    id: 206,
    ticker: 'PHI76',
    name: 'Philadelphia 76ers',
    category: 'NBA Teams',
    basePrice: 182.15,
    description: 'NBA team based in Philadelphia. Track confidence in the 76ers\' star talent, team chemistry, and playoff success.',
  },
  {
    id: 207,
    ticker: 'MIAHE',
    name: 'Miami Heat',
    category: 'NBA Teams',
    basePrice: 180.42,
    description: 'NBA team based in Miami. Trade confidence in the Heat\'s culture, coaching, and playoff resilience.',
  },
  {
    id: 208,
    ticker: 'DALMA',
    name: 'Dallas Mavericks',
    category: 'NBA Teams',
    basePrice: 178.89,
    description: 'NBA team based in Dallas. Track confidence in the Mavericks\' star duo, offensive firepower, and playoff potential.',
  },
  {
    id: 209,
    ticker: 'CLELA',
    name: 'Cleveland Cavaliers',
    category: 'NBA Teams',
    basePrice: 176.34,
    description: 'NBA team based in Cleveland. Trade confidence in the Cavaliers\' young core, development, and competitive progress.',
  },
  {
    id: 210,
    ticker: 'NYNKE',
    name: 'New York Knicks',
    category: 'NBA Teams',
    basePrice: 174.67,
    description: 'NBA team based in New York. Track confidence in the Knicks\' rebuild, roster moves, and playoff chances.',
  },
  {
    id: 211,
    ticker: 'LACLI',
    name: 'Los Angeles Clippers',
    category: 'NBA Teams',
    basePrice: 172.56,
    description: 'NBA team based in Los Angeles. Trade confidence in the Clippers\' star talent, depth, and championship window.',
  },
  {
    id: 212,
    ticker: 'OKCTH',
    name: 'Oklahoma City Thunder',
    category: 'NBA Teams',
    basePrice: 170.23,
    description: 'NBA team based in Oklahoma City. Track confidence in the Thunder\'s young stars, rebuild, and future potential.',
  },
  {
    id: 213,
    ticker: 'MINWO',
    name: 'Minnesota Timberwolves',
    category: 'NBA Teams',
    basePrice: 168.45,
    description: 'NBA team based in Minnesota. Trade confidence in the Timberwolves\' roster construction and playoff performance.',
  },
  {
    id: 214,
    ticker: 'SACKI',
    name: 'Sacramento Kings',
    category: 'NBA Teams',
    basePrice: 166.78,
    description: 'NBA team based in Sacramento. Track confidence in the Kings\' offensive system, young talent, and competitive growth.',
  },
  {
    id: 215,
    ticker: 'NOPEL',
    name: 'New Orleans Pelicans',
    category: 'NBA Teams',
    basePrice: 164.92,
    description: 'NBA team based in New Orleans. Trade confidence in the Pelicans\' young stars, depth, and playoff aspirations.',
  },
  {
    id: 216,
    ticker: 'ATLHA',
    name: 'Atlanta Hawks',
    category: 'NBA Teams',
    basePrice: 162.34,
    description: 'NBA team based in Atlanta. Track confidence in the Hawks\' backcourt, roster moves, and playoff contention.',
  },
  {
    id: 217,
    ticker: 'CHIBU',
    name: 'Chicago Bulls',
    category: 'NBA Teams',
    basePrice: 160.67,
    description: 'NBA team based in Chicago. Trade confidence in the Bulls\' roster, coaching, and competitive direction.',
  },
  {
    id: 218,
    ticker: 'TORRA',
    name: 'Toronto Raptors',
    category: 'NBA Teams',
    basePrice: 158.45,
    description: 'NBA team based in Toronto. Track confidence in the Raptors\' rebuild, young talent, and future development.',
  },
  {
    id: 219,
    ticker: 'INDIA',
    name: 'Indiana Pacers',
    category: 'NBA Teams',
    basePrice: 156.78,
    description: 'NBA team based in Indiana. Trade confidence in the Pacers\' fast-paced offense, young core, and growth.',
  },
  {
    id: 220,
    ticker: 'ORLMA',
    name: 'Orlando Magic',
    category: 'NBA Teams',
    basePrice: 154.56,
    description: 'NBA team based in Orlando. Track confidence in the Magic\'s young talent, defensive identity, and rebuild progress.',
  },
  {
    id: 221,
    ticker: 'WASWI',
    name: 'Washington Wizards',
    category: 'NBA Teams',
    basePrice: 152.34,
    description: 'NBA team based in Washington. Trade confidence in the Wizards\' rebuild, draft strategy, and future direction.',
  },
  {
    id: 222,
    ticker: 'CHAHO',
    name: 'Charlotte Hornets',
    category: 'NBA Teams',
    basePrice: 150.67,
    description: 'NBA team based in Charlotte. Track confidence in the Hornets\' young stars, development, and competitive progress.',
  },
  {
    id: 223,
    ticker: 'DETPI',
    name: 'Detroit Pistons',
    category: 'NBA Teams',
    basePrice: 148.45,
    description: 'NBA team based in Detroit. Trade confidence in the Pistons\' rebuild, young core, and future potential.',
  },
  {
    id: 224,
    ticker: 'BROKE',
    name: 'Brooklyn Nets',
    category: 'NBA Teams',
    basePrice: 146.78,
    description: 'NBA team based in Brooklyn. Track confidence in the Nets\' rebuild, roster moves, and competitive direction.',
  },
  {
    id: 225,
    ticker: 'UTAJA',
    name: 'Utah Jazz',
    category: 'NBA Teams',
    basePrice: 144.56,
    description: 'NBA team based in Utah. Trade confidence in the Jazz\'s rebuild, young talent, and development strategy.',
  },
  {
    id: 226,
    ticker: 'PORTR',
    name: 'Portland Trail Blazers',
    category: 'NBA Teams',
    basePrice: 142.34,
    description: 'NBA team based in Portland. Track confidence in the Trail Blazers\' rebuild, draft picks, and future direction.',
  },
  {
    id: 227,
    ticker: 'HOURO',
    name: 'Houston Rockets',
    category: 'NBA Teams',
    basePrice: 140.67,
    description: 'NBA team based in Houston. Trade confidence in the Rockets\' young core, development, and rebuild progress.',
  },
  {
    id: 228,
    ticker: 'MEMGR',
    name: 'Memphis Grizzlies',
    category: 'NBA Teams',
    basePrice: 138.45,
    description: 'NBA team based in Memphis. Track confidence in the Grizzlies\' young stars, culture, and competitive potential.',
  },
  {
    id: 229,
    ticker: 'SANSP',
    name: 'San Antonio Spurs',
    category: 'NBA Teams',
    basePrice: 136.78,
    description: 'NBA team based in San Antonio. Trade confidence in the Spurs\' rebuild, young talent, and future development.',
  },
];

/**
 * Get entity by ID
 */
export const getEntityById = (id: number): EntityData | undefined => {
  return ENTITIES.find(entity => entity.id === id);
};

/**
 * Get entity by ticker
 */
export const getEntityByTicker = (ticker: string): EntityData | undefined => {
  return ENTITIES.find(entity => entity.ticker === ticker);
};

/**
 * Get all entities
 */
export const getAllEntities = (): EntityData[] => {
  return ENTITIES;
};

/**
 * Get entities by category
 */
export const getEntitiesByCategory = (category: string): EntityData[] => {
  return ENTITIES.filter(entity => entity.category === category);
};

/**
 * Get entity by name (case-insensitive)
 */
export const getEntityByName = (name: string): EntityData | undefined => {
  return ENTITIES.find(entity => 
    entity.name.toLowerCase() === name.toLowerCase()
  );
};

