/**
 * Centralized Mock Entity Data
 * This ensures consistent entity information across all screens
 */

export interface MockEntity {
  id: number;
  ticker: string;
  name: string;
  category: string;
  basePrice: number;
  description: string;
}

// Single source of truth for all entities
export const MOCK_ENTITIES: MockEntity[] = [
  {
    id: 10,
    ticker: 'TRUMP',
    name: 'Donald Trump',
    category: 'Political Figures',
    basePrice: 142.55,
    description: 'Former president and political figure. Trade confidence in political influence and electoral prospects.',
  },
  // Influencers
  {
    id: 11,
    ticker: 'ALIX',
    name: 'Alix Earle',
    category: 'Influencers',
    basePrice: 200.47,
    description: 'TikTok influencer and content creator. Track confidence in Alix Earle\'s influence, brand partnerships, and audience growth.',
  },
  {
    id: 12,
    ticker: 'MRBST',
    name: 'MrBeast',
    category: 'Influencers',
    basePrice: 195.83,
    description: 'YouTube creator and philanthropist. Trade confidence in MrBeast\'s channel growth, business ventures, and social impact initiatives.',
  },
  {
    id: 14,
    ticker: 'KACEN',
    name: 'Kai Cenat',
    category: 'Influencers',
    basePrice: 185.29,
    description: 'Twitch streamer and content creator. Trade confidence in Kai Cenat\'s streaming success, audience engagement, and career trajectory.',
  },
  {
    id: 20,
    ticker: 'CDAME',
    name: 'Charli D\'Amelio',
    category: 'Influencers',
    basePrice: 182.56,
    description: 'TikTok star and social media influencer. Trade confidence in Charli D\'Amelio\'s influence, brand deals, and career growth.',
  },
  {
    id: 15,
    ticker: 'LPAUL',
    name: 'Logan Paul',
    category: 'Influencers',
    basePrice: 178.91,
    description: 'YouTube creator, boxer, and entrepreneur. Track confidence in Logan Paul\'s ventures, fight career, and business success.',
  },
  {
    id: 19,
    ticker: 'JPAUL',
    name: 'Jake Paul',
    category: 'Influencers',
    basePrice: 175.34,
    description: 'YouTube creator, boxer, and entrepreneur. Track confidence in Jake Paul\'s boxing career, business ventures, and public profile.',
  },
  {
    id: 18,
    ticker: 'ACOOP',
    name: 'Alex Cooper',
    category: 'Influencers',
    basePrice: 172.68,
    description: 'Podcast host and media personality. Trade confidence in Alex Cooper\'s podcast success, brand expansion, and media influence.',
  },
  {
    id: 16,
    ticker: 'ECHAM',
    name: 'Emma Chamberlain',
    category: 'Influencers',
    basePrice: 162.42,
    description: 'YouTube creator and fashion influencer. Trade confidence in Emma Chamberlain\'s brand partnerships, content creation, and influence.',
  },
  {
    id: 17,
    ticker: 'AROSS',
    name: 'Adin Ross',
    category: 'Influencers',
    basePrice: 145.76,
    description: 'Twitch streamer and content creator. Track confidence in Adin Ross\'s streaming career, collaborations, and audience growth.',
  },
  {
    id: 13,
    ticker: 'ATATE',
    name: 'Andrew Tate',
    category: 'Influencers',
    basePrice: 128.13,
    description: 'Controversial internet personality and former kickboxer. Track confidence in Andrew Tate\'s influence and media presence.',
  },
  // Political Figures
  {
    id: 31,
    ticker: 'JBIDN',
    name: 'Joe Biden',
    category: 'Political Figures',
    basePrice: 141.23,
    description: 'Current president of the United States. Track confidence in Joe Biden\'s policy decisions, approval ratings, and political influence.',
  },
  {
    id: 32,
    ticker: 'KHARR',
    name: 'Kamala Harris',
    category: 'Political Figures',
    basePrice: 138.67,
    description: 'Vice President of the United States. Trade confidence in Kamala Harris\'s political standing, policy impact, and future prospects.',
  },
  {
    id: 33,
    ticker: 'RDESA',
    name: 'Ron DeSantis',
    category: 'Political Figures',
    basePrice: 135.89,
    description: 'Governor of Florida and political figure. Track confidence in Ron DeSantis\'s political influence, policy decisions, and electoral prospects.',
  },
  {
    id: 34,
    ticker: 'AOC',
    name: 'Alexandria Ocasio-Cortez',
    category: 'Political Figures',
    basePrice: 133.42,
    description: 'U.S. Representative and progressive political figure. Trade confidence in Alexandria Ocasio-Cortez\'s policy advocacy and political influence.',
  },
  {
    id: 35,
    ticker: 'VRAMA',
    name: 'Vivek Ramaswamy',
    category: 'Political Figures',
    basePrice: 130.76,
    description: 'Entrepreneur and political figure. Track confidence in Vivek Ramaswamy\'s political influence, policy positions, and public profile.',
  },
  {
    id: 36,
    ticker: 'NHALE',
    name: 'Nikki Haley',
    category: 'Political Figures',
    basePrice: 128.54,
    description: 'Former U.N. Ambassador and political figure. Trade confidence in Nikki Haley\'s political standing, policy influence, and electoral prospects.',
  },
  {
    id: 37,
    ticker: 'GNEWS',
    name: 'Gavin Newsom',
    category: 'Political Figures',
    basePrice: 126.18,
    description: 'Governor of California and political figure. Track confidence in Gavin Newsom\'s policy decisions, political influence, and future prospects.',
  },
  {
    id: 38,
    ticker: 'TCARS',
    name: 'Tucker Carlson',
    category: 'Political Figures',
    basePrice: 123.91,
    description: 'Media personality and political commentator. Trade confidence in Tucker Carlson\'s influence, media presence, and political impact.',
  },
  {
    id: 39,
    ticker: 'BSAND',
    name: 'Bernie Sanders',
    category: 'Political Figures',
    basePrice: 121.45,
    description: 'U.S. Senator and progressive political figure. Track confidence in Bernie Sanders\'s policy advocacy, political influence, and public support.',
  },
  // Startups
  {
    id: 40,
    ticker: 'CLUEL',
    name: 'Cluely',
    category: 'Startups',
    basePrice: 175.63,
    description: 'AI-powered startup focused on intelligent solutions. Trade confidence in Cluely\'s product development, market adoption, and growth trajectory.',
  },
  {
    id: 41,
    ticker: 'PERPL',
    name: 'Perplexity',
    category: 'Startups',
    basePrice: 188.92,
    description: 'AI search and research platform. Track confidence in Perplexity\'s user growth, product innovation, and competitive positioning.',
  },
  {
    id: 42,
    ticker: 'ABRID',
    name: 'Abridge',
    category: 'Startups',
    basePrice: 162.47,
    description: 'AI-powered medical transcription and documentation platform. Trade confidence in Abridge\'s healthcare technology adoption and market expansion.',
  },
  {
    id: 43,
    ticker: 'REPLI',
    name: 'Replit',
    category: 'Startups',
    basePrice: 195.28,
    description: 'Cloud-based development platform and AI coding assistant. Track confidence in Replit\'s developer adoption, platform growth, and product evolution.',
  },
  {
    id: 44,
    ticker: 'MERCU',
    name: 'Mercury',
    category: 'Startups',
    basePrice: 171.85,
    description: 'Banking platform for startups. Trade confidence in Mercury\'s financial services growth, customer acquisition, and market expansion.',
  },
  {
    id: 45,
    ticker: 'CHRAC',
    name: 'Character.AI',
    category: 'Startups',
    basePrice: 182.16,
    description: 'AI character conversation platform. Track confidence in Character.AI\'s user engagement, content creation, and platform development.',
  },
  {
    id: 46,
    ticker: 'LUMAI',
    name: 'Luma AI',
    category: 'Startups',
    basePrice: 169.74,
    description: '3D rendering and AI visualization technology. Trade confidence in Luma AI\'s product innovation, market adoption, and technology advancement.',
  },
  {
    id: 47,
    ticker: 'CURSO',
    name: 'Cursor',
    category: 'Startups',
    basePrice: 190.53,
    description: 'AI-powered code editor for developers. Track confidence in Cursor\'s developer adoption, product development, and market positioning.',
  },
  {
    id: 48,
    ticker: 'VAPI',
    name: 'Vapi',
    category: 'Startups',
    basePrice: 157.39,
    description: 'AI voice API platform. Trade confidence in Vapi\'s API adoption, developer ecosystem growth, and product innovation.',
  },
  {
    id: 49,
    ticker: 'ANYSP',
    name: 'Anysphere',
    category: 'Startups',
    basePrice: 164.82,
    description: 'AI development tools and infrastructure. Track confidence in Anysphere\'s product development, developer adoption, and market growth.',
  },
  // NFL Teams
  {
    id: 50,
    ticker: 'KCCHF',
    name: 'Kansas City Chiefs',
    category: 'NFL',
    basePrice: 195.23,
    description: 'NFL team. Trade confidence in the Chiefs\' performance, playoff prospects, and championship potential.',
  },
  {
    id: 51,
    ticker: 'BUFBI',
    name: 'Buffalo Bills',
    category: 'NFL',
    basePrice: 188.47,
    description: 'NFL team. Track confidence in the Bills\' season performance, playoff chances, and Super Bowl aspirations.',
  },
  {
    id: 52,
    ticker: 'BALRA',
    name: 'Baltimore Ravens',
    category: 'NFL',
    basePrice: 182.65,
    description: 'NFL team. Trade confidence in the Ravens\' performance, division standing, and playoff potential.',
  },
  {
    id: 53,
    ticker: 'SF49E',
    name: 'San Francisco 49ers',
    category: 'NFL',
    basePrice: 179.34,
    description: 'NFL team. Track confidence in the 49ers\' season success, playoff run, and championship contention.',
  },
  {
    id: 54,
    ticker: 'DALCO',
    name: 'Dallas Cowboys',
    category: 'NFL',
    basePrice: 175.89,
    description: 'NFL team. Trade confidence in the Cowboys\' performance, division title chances, and playoff success.',
  },
  {
    id: 55,
    ticker: 'PHIEA',
    name: 'Philadelphia Eagles',
    category: 'NFL',
    basePrice: 172.56,
    description: 'NFL team. Track confidence in the Eagles\' season performance, playoff prospects, and Super Bowl potential.',
  },
  {
    id: 56,
    ticker: 'DETLI',
    name: 'Detroit Lions',
    category: 'NFL',
    basePrice: 169.23,
    description: 'NFL team. Trade confidence in the Lions\' performance, division standing, and playoff chances.',
  },
  {
    id: 57,
    ticker: 'MIA DO',
    name: 'Miami Dolphins',
    category: 'NFL',
    basePrice: 166.78,
    description: 'NFL team. Track confidence in the Dolphins\' season success, playoff run, and championship aspirations.',
  },
  {
    id: 58,
    ticker: 'CINBE',
    name: 'Cincinnati Bengals',
    category: 'NFL',
    basePrice: 163.45,
    description: 'NFL team. Trade confidence in the Bengals\' performance, division title chances, and playoff potential.',
  },
  {
    id: 59,
    ticker: 'GBPA',
    name: 'Green Bay Packers',
    category: 'NFL',
    basePrice: 160.12,
    description: 'NFL team. Track confidence in the Packers\' season performance, playoff prospects, and Super Bowl contention.',
  },
  {
    id: 60,
    ticker: 'HOU TE',
    name: 'Houston Texans',
    category: 'NFL',
    basePrice: 157.89,
    description: 'NFL team. Trade confidence in the Texans\' performance, division standing, and playoff chances.',
  },
  {
    id: 61,
    ticker: 'CLEBR',
    name: 'Cleveland Browns',
    category: 'NFL',
    basePrice: 154.67,
    description: 'NFL team. Track confidence in the Browns\' season success, playoff run, and championship potential.',
  },
  {
    id: 62,
    ticker: 'NYJET',
    name: 'New York Jets',
    category: 'NFL',
    basePrice: 151.34,
    description: 'NFL team. Trade confidence in the Jets\' performance, division title chances, and playoff prospects.',
  },
  {
    id: 63,
    ticker: 'LARAM',
    name: 'Los Angeles Rams',
    category: 'NFL',
    basePrice: 148.91,
    description: 'NFL team. Track confidence in the Rams\' season performance, playoff chances, and Super Bowl aspirations.',
  },
  {
    id: 64,
    ticker: 'TBBUC',
    name: 'Tampa Bay Buccaneers',
    category: 'NFL',
    basePrice: 145.78,
    description: 'NFL team. Trade confidence in the Buccaneers\' performance, division standing, and playoff potential.',
  },
  {
    id: 65,
    ticker: 'INDCO',
    name: 'Indianapolis Colts',
    category: 'NFL',
    basePrice: 142.56,
    description: 'NFL team. Track confidence in the Colts\' season success, playoff run, and championship contention.',
  },
  {
    id: 66,
    ticker: 'JAXJA',
    name: 'Jacksonville Jaguars',
    category: 'NFL',
    basePrice: 139.23,
    description: 'NFL team. Trade confidence in the Jaguars\' performance, division title chances, and playoff prospects.',
  },
  {
    id: 67,
    ticker: 'PITST',
    name: 'Pittsburgh Steelers',
    category: 'NFL',
    basePrice: 136.89,
    description: 'NFL team. Track confidence in the Steelers\' season performance, playoff chances, and Super Bowl potential.',
  },
  {
    id: 68,
    ticker: 'ATLFA',
    name: 'Atlanta Falcons',
    category: 'NFL',
    basePrice: 133.67,
    description: 'NFL team. Trade confidence in the Falcons\' performance, division standing, and playoff aspirations.',
  },
  {
    id: 69,
    ticker: 'NO SA',
    name: 'New Orleans Saints',
    category: 'NFL',
    basePrice: 130.45,
    description: 'NFL team. Track confidence in the Saints\' season success, playoff run, and championship contention.',
  },
  {
    id: 70,
    ticker: 'SEA SE',
    name: 'Seattle Seahawks',
    category: 'NFL',
    basePrice: 127.23,
    description: 'NFL team. Trade confidence in the Seahawks\' performance, division title chances, and playoff potential.',
  },
  {
    id: 71,
    ticker: 'LACH',
    name: 'Los Angeles Chargers',
    category: 'NFL',
    basePrice: 124.89,
    description: 'NFL team. Track confidence in the Chargers\' season performance, playoff prospects, and Super Bowl aspirations.',
  },
  {
    id: 72,
    ticker: 'DENBR',
    name: 'Denver Broncos',
    category: 'NFL',
    basePrice: 121.67,
    description: 'NFL team. Trade confidence in the Broncos\' performance, division standing, and playoff chances.',
  },
  {
    id: 73,
    ticker: 'LVRAI',
    name: 'Las Vegas Raiders',
    category: 'NFL',
    basePrice: 118.45,
    description: 'NFL team. Track confidence in the Raiders\' season success, playoff run, and championship potential.',
  },
  {
    id: 74,
    ticker: 'TEN TI',
    name: 'Tennessee Titans',
    category: 'NFL',
    basePrice: 115.23,
    description: 'NFL team. Trade confidence in the Titans\' performance, division title chances, and playoff prospects.',
  },
  {
    id: 75,
    ticker: 'MINVI',
    name: 'Minnesota Vikings',
    category: 'NFL',
    basePrice: 112.89,
    description: 'NFL team. Track confidence in the Vikings\' season performance, playoff chances, and Super Bowl contention.',
  },
  {
    id: 76,
    ticker: 'CHIBE',
    name: 'Chicago Bears',
    category: 'NFL',
    basePrice: 109.67,
    description: 'NFL team. Trade confidence in the Bears\' performance, division standing, and playoff aspirations.',
  },
  {
    id: 77,
    ticker: 'WASCO',
    name: 'Washington Commanders',
    category: 'NFL',
    basePrice: 106.45,
    description: 'NFL team. Track confidence in the Commanders\' season success, playoff run, and championship potential.',
  },
  {
    id: 78,
    ticker: 'NYGIA',
    name: 'New York Giants',
    category: 'NFL',
    basePrice: 103.23,
    description: 'NFL team. Trade confidence in the Giants\' performance, division title chances, and playoff prospects.',
  },
  {
    id: 79,
    ticker: 'CARPA',
    name: 'Carolina Panthers',
    category: 'NFL',
    basePrice: 100.89,
    description: 'NFL team. Track confidence in the Panthers\' season performance, playoff chances, and Super Bowl aspirations.',
  },
  {
    id: 80,
    ticker: 'ARICA',
    name: 'Arizona Cardinals',
    category: 'NFL',
    basePrice: 97.67,
    description: 'NFL team. Trade confidence in the Cardinals\' performance, division standing, and playoff potential.',
  },
  {
    id: 81,
    ticker: 'NE PA',
    name: 'New England Patriots',
    category: 'NFL',
    basePrice: 94.45,
    description: 'NFL team. Track confidence in the Patriots\' season success, playoff run, and championship contention.',
  },
  // NBA Teams
  {
    id: 83,
    ticker: 'BOSCE',
    name: 'Boston Celtics',
    category: 'NBA',
    basePrice: 198.56,
    description: 'NBA team. Track confidence in the Celtics\' season performance, playoff run, and championship contention.',
  },
  {
    id: 84,
    ticker: 'DENNU',
    name: 'Denver Nuggets',
    category: 'NBA',
    basePrice: 192.34,
    description: 'NBA team. Trade confidence in the Nuggets\' performance, playoff prospects, and title defense.',
  },
  {
    id: 85,
    ticker: 'MILBU',
    name: 'Milwaukee Bucks',
    category: 'NBA',
    basePrice: 186.78,
    description: 'NBA team. Track confidence in the Bucks\' season success, playoff chances, and championship potential.',
  },
  {
    id: 86,
    ticker: 'PHO SU',
    name: 'Phoenix Suns',
    category: 'NBA',
    basePrice: 181.23,
    description: 'NBA team. Trade confidence in the Suns\' performance, division standing, and playoff aspirations.',
  },
  {
    id: 87,
    ticker: 'LALAK',
    name: 'Los Angeles Lakers',
    category: 'NBA',
    basePrice: 176.89,
    description: 'NBA team. Track confidence in the Lakers\' season performance, playoff run, and championship contention.',
  },
  {
    id: 88,
    ticker: 'GSWAR',
    name: 'Golden State Warriors',
    category: 'NBA',
    basePrice: 172.45,
    description: 'NBA team. Trade confidence in the Warriors\' performance, playoff prospects, and title chances.',
  },
  {
    id: 89,
    ticker: 'PHI76',
    name: 'Philadelphia 76ers',
    category: 'NBA',
    basePrice: 168.12,
    description: 'NBA team. Track confidence in the 76ers\' season success, playoff chances, and championship potential.',
  },
  {
    id: 90,
    ticker: 'MIAHE',
    name: 'Miami Heat',
    category: 'NBA',
    basePrice: 163.78,
    description: 'NBA team. Trade confidence in the Heat\'s performance, division title chances, and playoff run.',
  },
  {
    id: 91,
    ticker: 'DALMA',
    name: 'Dallas Mavericks',
    category: 'NBA',
    basePrice: 159.45,
    description: 'NBA team. Track confidence in the Mavericks\' season performance, playoff prospects, and championship aspirations.',
  },
  {
    id: 92,
    ticker: 'LACLI',
    name: 'Los Angeles Clippers',
    category: 'NBA',
    basePrice: 155.23,
    description: 'NBA team. Trade confidence in the Clippers\' performance, playoff chances, and title contention.',
  },
  {
    id: 93,
    ticker: 'CLE CA',
    name: 'Cleveland Cavaliers',
    category: 'NBA',
    basePrice: 150.89,
    description: 'NBA team. Track confidence in the Cavaliers\' season success, playoff run, and championship potential.',
  },
  {
    id: 94,
    ticker: 'NY KN',
    name: 'New York Knicks',
    category: 'NBA',
    basePrice: 146.67,
    description: 'NBA team. Trade confidence in the Knicks\' performance, division standing, and playoff prospects.',
  },
  {
    id: 95,
    ticker: 'OKCTH',
    name: 'Oklahoma City Thunder',
    category: 'NBA',
    basePrice: 142.34,
    description: 'NBA team. Track confidence in the Thunder\'s season performance, playoff chances, and championship aspirations.',
  },
  {
    id: 96,
    ticker: 'MIN TI',
    name: 'Minnesota Timberwolves',
    category: 'NBA',
    basePrice: 138.12,
    description: 'NBA team. Track confidence in the Timberwolves\' performance, playoff run, and title contention.',
  },
  {
    id: 97,
    ticker: 'SAC KI',
    name: 'Sacramento Kings',
    category: 'NBA',
    basePrice: 133.89,
    description: 'NBA team. Trade confidence in the Kings\' season success, playoff prospects, and championship potential.',
  },
  {
    id: 98,
    ticker: 'NO PE',
    name: 'New Orleans Pelicans',
    category: 'NBA',
    basePrice: 129.67,
    description: 'NBA team. Track confidence in the Pelicans\' performance, division title chances, and playoff aspirations.',
  },
  {
    id: 99,
    ticker: 'ATLHA',
    name: 'Atlanta Hawks',
    category: 'NBA',
    basePrice: 125.45,
    description: 'NBA team. Trade confidence in the Hawks\' season performance, playoff chances, and championship contention.',
  },
  {
    id: 100,
    ticker: 'CHIBU',
    name: 'Chicago Bulls',
    category: 'NBA',
    basePrice: 121.23,
    description: 'NBA team. Track confidence in the Bulls\' performance, playoff run, and title potential.',
  },
  {
    id: 101,
    ticker: 'IND PA',
    name: 'Indiana Pacers',
    category: 'NBA',
    basePrice: 117.89,
    description: 'NBA team. Trade confidence in the Pacers\' season success, playoff prospects, and championship aspirations.',
  },
  {
    id: 102,
    ticker: 'ORLMA',
    name: 'Orlando Magic',
    category: 'NBA',
    basePrice: 113.67,
    description: 'NBA team. Track confidence in the Magic\'s performance, division standing, and playoff chances.',
  },
  {
    id: 103,
    ticker: 'TORRA',
    name: 'Toronto Raptors',
    category: 'NBA',
    basePrice: 109.45,
    description: 'NBA team. Trade confidence in the Raptors\' season performance, playoff run, and championship contention.',
  },
  {
    id: 104,
    ticker: 'BRO NE',
    name: 'Brooklyn Nets',
    category: 'NBA',
    basePrice: 105.23,
    description: 'NBA team. Track confidence in the Nets\' performance, playoff prospects, and title aspirations.',
  },
  {
    id: 105,
    ticker: 'UTA JA',
    name: 'Utah Jazz',
    category: 'NBA',
    basePrice: 101.89,
    description: 'NBA team. Trade confidence in the Jazz\'s season success, playoff chances, and championship potential.',
  },
  {
    id: 106,
    ticker: 'HOU RO',
    name: 'Houston Rockets',
    category: 'NBA',
    basePrice: 97.67,
    description: 'NBA team. Track confidence in the Rockets\' performance, division title chances, and playoff run.',
  },
  {
    id: 107,
    ticker: 'MEM GR',
    name: 'Memphis Grizzlies',
    category: 'NBA',
    basePrice: 93.45,
    description: 'NBA team. Trade confidence in the Grizzlies\' season performance, playoff prospects, and championship contention.',
  },
  {
    id: 108,
    ticker: 'PORTR',
    name: 'Portland Trail Blazers',
    category: 'NBA',
    basePrice: 89.23,
    description: 'NBA team. Track confidence in the Trail Blazers\' performance, playoff chances, and title aspirations.',
  },
  {
    id: 109,
    ticker: 'SA SP',
    name: 'San Antonio Spurs',
    category: 'NBA',
    basePrice: 85.12,
    description: 'NBA team. Trade confidence in the Spurs\' season success, playoff run, and championship potential.',
  },
  {
    id: 110,
    ticker: 'CHA HO',
    name: 'Charlotte Hornets',
    category: 'NBA',
    basePrice: 80.89,
    description: 'NBA team. Track confidence in the Hornets\' performance, division standing, and playoff prospects.',
  },
  {
    id: 111,
    ticker: 'DET PI',
    name: 'Detroit Pistons',
    category: 'NBA',
    basePrice: 76.67,
    description: 'NBA team. Trade confidence in the Pistons\' season performance, playoff chances, and championship aspirations.',
  },
  {
    id: 112,
    ticker: 'WAS WI',
    name: 'Washington Wizards',
    category: 'NBA',
    basePrice: 72.45,
    description: 'NBA team. Track confidence in the Wizards\' performance, playoff run, and title contention.',
  },
  // College Basketball Teams
  {
    id: 113,
    ticker: 'DUKE',
    name: 'Duke',
    category: 'College Basketball',
    basePrice: 198.45,
    description: 'College basketball team. Track confidence in Duke\'s season performance, tournament run, and championship potential.',
  },
  {
    id: 114,
    ticker: 'KENT',
    name: 'Kentucky',
    category: 'College Basketball',
    basePrice: 195.23,
    description: 'College basketball team. Trade confidence in Kentucky\'s performance, tournament prospects, and title chances.',
  },
  {
    id: 115,
    ticker: 'UNC',
    name: 'North Carolina',
    category: 'College Basketball',
    basePrice: 192.67,
    description: 'College basketball team. Track confidence in North Carolina\'s season success, tournament run, and championship aspirations.',
  },
  {
    id: 116,
    ticker: 'KAN',
    name: 'Kansas',
    category: 'College Basketball',
    basePrice: 189.89,
    description: 'College basketball team. Trade confidence in Kansas\'s performance, tournament chances, and title contention.',
  },
  {
    id: 117,
    ticker: 'UCLA',
    name: 'UCLA',
    category: 'College Basketball',
    basePrice: 187.34,
    description: 'College basketball team. Track confidence in UCLA\'s season performance, tournament prospects, and championship potential.',
  },
  {
    id: 118,
    ticker: 'MICHST',
    name: 'Michigan State',
    category: 'College Basketball',
    basePrice: 184.78,
    description: 'College basketball team. Trade confidence in Michigan State\'s performance, tournament run, and title aspirations.',
  },
  {
    id: 119,
    ticker: 'IND',
    name: 'Indiana',
    category: 'College Basketball',
    basePrice: 182.12,
    description: 'College basketball team. Track confidence in Indiana\'s season success, tournament chances, and championship contention.',
  },
  {
    id: 120,
    ticker: 'ARIZ',
    name: 'Arizona',
    category: 'College Basketball',
    basePrice: 179.56,
    description: 'College basketball team. Trade confidence in Arizona\'s performance, tournament prospects, and title potential.',
  },
  {
    id: 121,
    ticker: 'UCONN',
    name: 'UConn',
    category: 'College Basketball',
    basePrice: 176.89,
    description: 'College basketball team. Track confidence in UConn\'s season performance, tournament run, and championship aspirations.',
  },
  {
    id: 122,
    ticker: 'LOU',
    name: 'Louisville',
    category: 'College Basketball',
    basePrice: 174.23,
    description: 'College basketball team. Trade confidence in Louisville\'s performance, tournament chances, and title contention.',
  },
  {
    id: 123,
    ticker: 'VILL',
    name: 'Villanova',
    category: 'College Basketball',
    basePrice: 171.67,
    description: 'College basketball team. Track confidence in Villanova\'s season success, tournament prospects, and championship potential.',
  },
  {
    id: 124,
    ticker: 'SYR',
    name: 'Syracuse',
    category: 'College Basketball',
    basePrice: 169.12,
    description: 'College basketball team. Trade confidence in Syracuse\'s performance, tournament run, and title aspirations.',
  },
  {
    id: 125,
    ticker: 'OHST',
    name: 'Ohio State',
    category: 'College Basketball',
    basePrice: 166.56,
    description: 'College basketball team. Track confidence in Ohio State\'s season performance, tournament chances, and championship contention.',
  },
  {
    id: 126,
    ticker: 'MICH',
    name: 'Michigan',
    category: 'College Basketball',
    basePrice: 163.89,
    description: 'College basketball team. Trade confidence in Michigan\'s performance, tournament prospects, and title potential.',
  },
  {
    id: 127,
    ticker: 'TEX',
    name: 'Texas',
    category: 'College Basketball',
    basePrice: 161.34,
    description: 'College basketball team. Track confidence in Texas\'s season success, tournament run, and championship aspirations.',
  },
  {
    id: 128,
    ticker: 'GONZ',
    name: 'Gonzaga',
    category: 'College Basketball',
    basePrice: 158.78,
    description: 'College basketball team. Trade confidence in Gonzaga\'s performance, tournament chances, and title contention.',
  },
  {
    id: 129,
    ticker: 'PUR',
    name: 'Purdue',
    category: 'College Basketball',
    basePrice: 156.12,
    description: 'College basketball team. Track confidence in Purdue\'s season performance, tournament prospects, and championship potential.',
  },
  {
    id: 130,
    ticker: 'ILL',
    name: 'Illinois',
    category: 'College Basketball',
    basePrice: 153.56,
    description: 'College basketball team. Trade confidence in Illinois\'s performance, tournament run, and title aspirations.',
  },
  {
    id: 131,
    ticker: 'WISC',
    name: 'Wisconsin',
    category: 'College Basketball',
    basePrice: 150.89,
    description: 'College basketball team. Track confidence in Wisconsin\'s season success, tournament chances, and championship contention.',
  },
  {
    id: 132,
    ticker: 'FLA',
    name: 'Florida',
    category: 'College Basketball',
    basePrice: 148.23,
    description: 'College basketball team. Trade confidence in Florida\'s performance, tournament prospects, and title potential.',
  },
  {
    id: 133,
    ticker: 'ARK',
    name: 'Arkansas',
    category: 'College Basketball',
    basePrice: 145.67,
    description: 'College basketball team. Track confidence in Arkansas\'s season performance, tournament run, and championship aspirations.',
  },
  {
    id: 134,
    ticker: 'TENN',
    name: 'Tennessee',
    category: 'College Basketball',
    basePrice: 143.12,
    description: 'College basketball team. Trade confidence in Tennessee\'s performance, tournament chances, and title contention.',
  },
  {
    id: 135,
    ticker: 'UVA',
    name: 'Virginia',
    category: 'College Basketball',
    basePrice: 140.56,
    description: 'College basketball team. Track confidence in Virginia\'s season success, tournament prospects, and championship potential.',
  },
  {
    id: 136,
    ticker: 'MD',
    name: 'Maryland',
    category: 'College Basketball',
    basePrice: 137.89,
    description: 'College basketball team. Trade confidence in Maryland\'s performance, tournament run, and title aspirations.',
  },
  {
    id: 137,
    ticker: 'AUB',
    name: 'Auburn',
    category: 'College Basketball',
    basePrice: 135.34,
    description: 'College basketball team. Track confidence in Auburn\'s season performance, tournament chances, and championship contention.',
  },
  {
    id: 138,
    ticker: 'ALA',
    name: 'Alabama',
    category: 'College Basketball',
    basePrice: 132.78,
    description: 'College basketball team. Trade confidence in Alabama\'s performance, tournament prospects, and title potential.',
  },
  {
    id: 139,
    ticker: 'BAYL',
    name: 'Baylor',
    category: 'College Basketball',
    basePrice: 130.12,
    description: 'College basketball team. Track confidence in Baylor\'s season success, tournament run, and championship aspirations.',
  },
  {
    id: 140,
    ticker: 'TXTECH',
    name: 'Texas Tech',
    category: 'College Basketball',
    basePrice: 127.56,
    description: 'College basketball team. Trade confidence in Texas Tech\'s performance, tournament chances, and title contention.',
  },
  {
    id: 141,
    ticker: 'IOWAST',
    name: 'Iowa State',
    category: 'College Basketball',
    basePrice: 124.89,
    description: 'College basketball team. Track confidence in Iowa State\'s season performance, tournament prospects, and championship potential.',
  },
  {
    id: 142,
    ticker: 'CREI',
    name: 'Creighton',
    category: 'College Basketball',
    basePrice: 122.23,
    description: 'College basketball team. Trade confidence in Creighton\'s performance, tournament run, and title aspirations.',
  },
  {
    id: 143,
    ticker: 'ORE',
    name: 'Oregon',
    category: 'College Basketball',
    basePrice: 119.67,
    description: 'College basketball team. Track confidence in Oregon\'s season success, tournament chances, and championship contention.',
  },
  {
    id: 144,
    ticker: 'WASH',
    name: 'Washington',
    category: 'College Basketball',
    basePrice: 117.12,
    description: 'College basketball team. Trade confidence in Washington\'s performance, tournament prospects, and title potential.',
  },
  {
    id: 145,
    ticker: 'AZST',
    name: 'Arizona State',
    category: 'College Basketball',
    basePrice: 114.56,
    description: 'College basketball team. Track confidence in Arizona State\'s season performance, tournament run, and championship aspirations.',
  },
  {
    id: 146,
    ticker: 'SDST',
    name: 'San Diego State',
    category: 'College Basketball',
    basePrice: 111.89,
    description: 'College basketball team. Trade confidence in San Diego State\'s performance, tournament chances, and title contention.',
  },
  {
    id: 147,
    ticker: 'MEM',
    name: 'Memphis',
    category: 'College Basketball',
    basePrice: 109.34,
    description: 'College basketball team. Track confidence in Memphis\'s season success, tournament prospects, and championship potential.',
  },
  {
    id: 148,
    ticker: 'STJ',
    name: 'St. John\'s',
    category: 'College Basketball',
    basePrice: 106.78,
    description: 'College basketball team. Trade confidence in St. John\'s performance, tournament run, and title aspirations.',
  },
  {
    id: 149,
    ticker: 'SETON',
    name: 'Seton Hall',
    category: 'College Basketball',
    basePrice: 104.12,
    description: 'College basketball team. Track confidence in Seton Hall\'s season performance, tournament chances, and championship contention.',
  },
  {
    id: 150,
    ticker: 'GTWN',
    name: 'Georgetown',
    category: 'College Basketball',
    basePrice: 101.56,
    description: 'College basketball team. Trade confidence in Georgetown\'s performance, tournament prospects, and title potential.',
  },
  {
    id: 151,
    ticker: 'MIA',
    name: 'Miami (FL)',
    category: 'College Basketball',
    basePrice: 98.89,
    description: 'College basketball team. Track confidence in Miami\'s season success, tournament run, and championship aspirations.',
  },
  {
    id: 152,
    ticker: 'OKLA',
    name: 'Oklahoma',
    category: 'College Basketball',
    basePrice: 96.23,
    description: 'College basketball team. Trade confidence in Oklahoma\'s performance, tournament chances, and title contention.',
  },
  {
    id: 153,
    ticker: 'OKST',
    name: 'Oklahoma State',
    category: 'College Basketball',
    basePrice: 93.67,
    description: 'College basketball team. Track confidence in Oklahoma State\'s season performance, tournament prospects, and championship potential.',
  },
  {
    id: 154,
    ticker: 'NCST',
    name: 'NC State',
    category: 'College Basketball',
    basePrice: 91.12,
    description: 'College basketball team. Trade confidence in NC State\'s performance, tournament run, and title aspirations.',
  },
  {
    id: 155,
    ticker: 'IOWA',
    name: 'Iowa',
    category: 'College Basketball',
    basePrice: 88.56,
    description: 'College basketball team. Track confidence in Iowa\'s season success, tournament chances, and championship contention.',
  },
  {
    id: 156,
    ticker: 'MINN',
    name: 'Minnesota',
    category: 'College Basketball',
    basePrice: 85.89,
    description: 'College basketball team. Trade confidence in Minnesota\'s performance, tournament prospects, and title potential.',
  },
  {
    id: 157,
    ticker: 'NEB',
    name: 'Nebraska',
    category: 'College Basketball',
    basePrice: 83.34,
    description: 'College basketball team. Track confidence in Nebraska\'s season performance, tournament run, and championship aspirations.',
  },
  {
    id: 158,
    ticker: 'BYU',
    name: 'BYU',
    category: 'College Basketball',
    basePrice: 80.78,
    description: 'College basketball team. Trade confidence in BYU\'s performance, tournament chances, and title contention.',
  },
  {
    id: 159,
    ticker: 'WVU',
    name: 'West Virginia',
    category: 'College Basketball',
    basePrice: 78.12,
    description: 'College basketball team. Track confidence in West Virginia\'s season success, tournament prospects, and championship potential.',
  },
  {
    id: 160,
    ticker: 'DAY',
    name: 'Dayton',
    category: 'College Basketball',
    basePrice: 75.56,
    description: 'College basketball team. Trade confidence in Dayton\'s performance, tournament run, and title aspirations.',
  },
  {
    id: 161,
    ticker: 'VCU',
    name: 'VCU',
    category: 'College Basketball',
    basePrice: 72.89,
    description: 'College basketball team. Track confidence in VCU\'s season performance, tournament chances, and championship contention.',
  },
  {
    id: 162,
    ticker: 'LSU',
    name: 'LSU',
    category: 'College Basketball',
    basePrice: 70.23,
    description: 'College basketball team. Trade confidence in LSU\'s performance, tournament prospects, and title potential.',
  },
  // Hip Hop Artists
  {
    id: 163,
    ticker: 'KENDR',
    name: 'Kendrick Lamar',
    category: 'Hip Hop',
    basePrice: 198.45,
    description: 'Hip hop artist and rapper. Track confidence in Kendrick Lamar\'s album releases, chart performance, and cultural influence.',
  },
  {
    id: 164,
    ticker: 'JCOLE',
    name: 'J. Cole',
    category: 'Hip Hop',
    basePrice: 192.67,
    description: 'Hip hop artist and producer. Trade confidence in J. Cole\'s music releases, tours, and artistic evolution.',
  },
  {
    id: 165,
    ticker: 'EMINE',
    name: 'Eminem',
    category: 'Hip Hop',
    basePrice: 186.89,
    description: 'Hip hop artist and rapper. Track confidence in Eminem\'s album success, chart dominance, and legacy impact.',
  },
  {
    id: 166,
    ticker: 'NICKI',
    name: 'Nicki Minaj',
    category: 'Hip Hop',
    basePrice: 181.23,
    description: 'Hip hop artist and rapper. Trade confidence in Nicki Minaj\'s releases, collaborations, and chart performance.',
  },
  {
    id: 167,
    ticker: 'LILNA',
    name: 'Lil Nas X',
    category: 'Hip Hop',
    basePrice: 175.56,
    description: 'Hip hop artist and rapper. Track confidence in Lil Nas X\'s viral hits, album releases, and cultural impact.',
  },
  {
    id: 168,
    ticker: 'POSTM',
    name: 'Post Malone',
    category: 'Hip Hop',
    basePrice: 169.89,
    description: 'Hip hop artist and rapper. Trade confidence in Post Malone\'s chart success, album releases, and tour performances.',
  },
  {
    id: 169,
    ticker: 'TYLER',
    name: 'Tyler, The Creator',
    category: 'Hip Hop',
    basePrice: 164.12,
    description: 'Hip hop artist and producer. Track confidence in Tyler, The Creator\'s album releases, artistic evolution, and influence.',
  },
  {
    id: 170,
    ticker: 'ASAPR',
    name: 'A$AP Rocky',
    category: 'Hip Hop',
    basePrice: 158.45,
    description: 'Hip hop artist and rapper. Trade confidence in A$AP Rocky\'s music releases, fashion ventures, and cultural impact.',
  },
  {
    id: 171,
    ticker: 'CHILD',
    name: 'Childish Gambino',
    category: 'Hip Hop',
    basePrice: 152.78,
    description: 'Hip hop artist and multi-talented entertainer. Track confidence in Childish Gambino\'s releases, projects, and artistic evolution.',
  },
  {
    id: 172,
    ticker: 'DRAKE',
    name: 'Drake',
    category: 'Hip Hop',
    basePrice: 192.37,
    description: 'Grammy-winning rapper and record producer. Trade confidence in Drake\'s chart dominance, album releases, and business ventures.',
  },
  // Country Music Artists
  {
    id: 173,
    ticker: 'MORGA',
    name: 'Morgan Wallen',
    category: 'Country Music',
    basePrice: 195.34,
    description: 'Country music artist. Track confidence in Morgan Wallen\'s album releases, chart performance, and tour success.',
  },
  {
    id: 174,
    ticker: 'LUKE',
    name: 'Luke Combs',
    category: 'Country Music',
    basePrice: 189.67,
    description: 'Country music artist. Trade confidence in Luke Combs\'s music releases, chart dominance, and live performances.',
  },
  {
    id: 175,
    ticker: 'ZACH',
    name: 'Zach Bryan',
    category: 'Country Music',
    basePrice: 183.89,
    description: 'Country music artist. Track confidence in Zach Bryan\'s album success, chart performance, and growing fanbase.',
  },
  {
    id: 176,
    ticker: 'JASON',
    name: 'Jason Aldean',
    category: 'Country Music',
    basePrice: 178.23,
    description: 'Country music artist. Trade confidence in Jason Aldean\'s releases, tours, and chart performance.',
  },
  {
    id: 177,
    ticker: 'KENNY',
    name: 'Kenny Chesney',
    category: 'Country Music',
    basePrice: 172.56,
    description: 'Country music artist. Track confidence in Kenny Chesney\'s album releases, tour success, and chart dominance.',
  },
  {
    id: 178,
    ticker: 'THOMAS',
    name: 'Thomas Rhett',
    category: 'Country Music',
    basePrice: 166.89,
    description: 'Country music artist. Trade confidence in Thomas Rhett\'s music releases, chart performance, and live shows.',
  },
  {
    id: 179,
    ticker: 'CARRIE',
    name: 'Carrie Underwood',
    category: 'Country Music',
    basePrice: 161.23,
    description: 'Country music artist. Track confidence in Carrie Underwood\'s album success, chart performance, and tour performances.',
  },
  {
    id: 180,
    ticker: 'MIRAN',
    name: 'Miranda Lambert',
    category: 'Country Music',
    basePrice: 155.56,
    description: 'Country music artist. Trade confidence in Miranda Lambert\'s releases, chart success, and artistic evolution.',
  },
  {
    id: 181,
    ticker: 'ERIC',
    name: 'Eric Church',
    category: 'Country Music',
    basePrice: 149.89,
    description: 'Country music artist. Track confidence in Eric Church\'s album releases, tour success, and chart performance.',
  },
  {
    id: 182,
    ticker: 'CHRIS',
    name: 'Chris Stapleton',
    category: 'Country Music',
    basePrice: 144.12,
    description: 'Country music artist. Trade confidence in Chris Stapleton\'s music releases, chart dominance, and live performances.',
  },
  // Pop Music Artists
  {
    id: 183,
    ticker: 'HARRY',
    name: 'Harry Styles',
    category: 'Pop Music',
    basePrice: 197.89,
    description: 'Pop music artist. Track confidence in Harry Styles\'s album releases, chart performance, and tour success.',
  },
  {
    id: 184,
    ticker: 'BILLIE',
    name: 'Billie Eilish',
    category: 'Pop Music',
    basePrice: 192.23,
    description: 'Pop music artist. Trade confidence in Billie Eilish\'s music releases, chart dominance, and artistic evolution.',
  },
  {
    id: 185,
    ticker: 'DUA',
    name: 'Dua Lipa',
    category: 'Pop Music',
    basePrice: 186.56,
    description: 'Pop music artist. Track confidence in Dua Lipa\'s album success, chart performance, and tour performances.',
  },
  {
    id: 186,
    ticker: 'ARIAN',
    name: 'Ariana Grande',
    category: 'Pop Music',
    basePrice: 180.89,
    description: 'Pop music artist. Trade confidence in Ariana Grande\'s releases, chart success, and live shows.',
  },
  {
    id: 187,
    ticker: 'ED',
    name: 'Ed Sheeran',
    category: 'Pop Music',
    basePrice: 175.23,
    description: 'Pop music artist. Track confidence in Ed Sheeran\'s album releases, tour success, and chart dominance.',
  },
  {
    id: 188,
    ticker: 'BRUNO',
    name: 'Bruno Mars',
    category: 'Pop Music',
    basePrice: 169.56,
    description: 'Pop music artist. Trade confidence in Bruno Mars\'s music releases, chart performance, and live performances.',
  },
  {
    id: 189,
    ticker: 'JUSTIN',
    name: 'Justin Bieber',
    category: 'Pop Music',
    basePrice: 163.89,
    description: 'Pop music artist. Track confidence in Justin Bieber\'s album success, chart performance, and tour performances.',
  },
  {
    id: 190,
    ticker: 'SHAWN',
    name: 'Shawn Mendes',
    category: 'Pop Music',
    basePrice: 158.23,
    description: 'Pop music artist. Trade confidence in Shawn Mendes\'s releases, chart success, and live shows.',
  },
  {
    id: 191,
    ticker: 'LIZZO',
    name: 'Lizzo',
    category: 'Pop Music',
    basePrice: 152.56,
    description: 'Pop music artist. Track confidence in Lizzo\'s album releases, chart performance, and tour success.',
  },
  {
    id: 192,
    ticker: 'LADY',
    name: 'Lady Gaga',
    category: 'Pop Music',
    basePrice: 146.89,
    description: 'Pop music artist. Trade confidence in Lady Gaga\'s music releases, chart dominance, and artistic evolution.',
  },
];

/**
 * Get entity by ID
 */
export const getEntityById = (id: number): MockEntity | undefined => {
  return MOCK_ENTITIES.find(entity => entity.id === id);
};

/**
 * Get entity by ticker
 */
export const getEntityByTicker = (ticker: string): MockEntity | undefined => {
  return MOCK_ENTITIES.find(entity => entity.ticker === ticker);
};

/**
 * Get all entities
 */
export const getAllEntities = (): MockEntity[] => {
  return MOCK_ENTITIES;
};

/**
 * Get entities by category
 */
export const getEntitiesByCategory = (category: string): MockEntity[] => {
  return MOCK_ENTITIES.filter(entity => entity.category === category);
};

/**
 * Get entity by name (case-insensitive)
 */
export const getEntityByName = (name: string): MockEntity | undefined => {
  return MOCK_ENTITIES.find(entity => 
    entity.name.toLowerCase() === name.toLowerCase()
  );
};

