/**
 * Centralized Mock Entity Data
 * This ensures consistent entity information across all screens
 */

export interface MockEntity {
  id: number;
  ticker: string;
  name: string;
  category: string;
  basePrice: number;
  description: string;
}

// Single source of truth for all entities
export const MOCK_ENTITIES: MockEntity[] = [
  {
    id: 10,
    ticker: 'TRUMP',
    name: 'Donald Trump',
    category: 'Political Figures',
    basePrice: 142.55,
    description: 'Former president and political figure. Trade confidence in political influence and electoral prospects.',
  },
  // Influencers
  {
    id: 11,
    ticker: 'ALIX',
    name: 'Alix Earle',
    category: 'Influencers',
    basePrice: 200.47,
    description: 'TikTok influencer and content creator. Track confidence in Alix Earle\'s influence, brand partnerships, and audience growth.',
  },
  {
    id: 12,
    ticker: 'MRBST',
    name: 'MrBeast',
    category: 'Influencers',
    basePrice: 195.83,
    description: 'YouTube creator and philanthropist. Trade confidence in MrBeast\'s channel growth, business ventures, and social impact initiatives.',
  },
  {
    id: 14,
    ticker: 'KACEN',
    name: 'Kai Cenat',
    category: 'Influencers',
    basePrice: 185.29,
    description: 'Twitch streamer and content creator. Trade confidence in Kai Cenat\'s streaming success, audience engagement, and career trajectory.',
  },
  {
    id: 20,
    ticker: 'CDAME',
    name: 'Charli D\'Amelio',
    category: 'Influencers',
    basePrice: 182.56,
    description: 'TikTok star and social media influencer. Trade confidence in Charli D\'Amelio\'s influence, brand deals, and career growth.',
  },
  {
    id: 15,
    ticker: 'LPAUL',
    name: 'Logan Paul',
    category: 'Influencers',
    basePrice: 178.91,
    description: 'YouTube creator, boxer, and entrepreneur. Track confidence in Logan Paul\'s ventures, fight career, and business success.',
  },
  {
    id: 19,
    ticker: 'JPAUL',
    name: 'Jake Paul',
    category: 'Influencers',
    basePrice: 175.34,
    description: 'YouTube creator, boxer, and entrepreneur. Track confidence in Jake Paul\'s boxing career, business ventures, and public profile.',
  },
  {
    id: 18,
    ticker: 'ACOOP',
    name: 'Alex Cooper',
    category: 'Influencers',
    basePrice: 172.68,
    description: 'Podcast host and media personality. Trade confidence in Alex Cooper\'s podcast success, brand expansion, and media influence.',
  },
  {
    id: 16,
    ticker: 'ECHAM',
    name: 'Emma Chamberlain',
    category: 'Influencers',
    basePrice: 162.42,
    description: 'YouTube creator and fashion influencer. Trade confidence in Emma Chamberlain\'s brand partnerships, content creation, and influence.',
  },
  {
    id: 17,
    ticker: 'AROSS',
    name: 'Adin Ross',
    category: 'Influencers',
    basePrice: 145.76,
    description: 'Twitch streamer and content creator. Track confidence in Adin Ross\'s streaming career, collaborations, and audience growth.',
  },
  {
    id: 13,
    ticker: 'ATATE',
    name: 'Andrew Tate',
    category: 'Influencers',
    basePrice: 128.13,
    description: 'Controversial internet personality and former kickboxer. Track confidence in Andrew Tate\'s influence and media presence.',
  },
  // Music Artists
  {
    id: 21,
    ticker: 'TSWFT',
    name: 'Taylor Swift',
    category: 'Music Artists',
    basePrice: 198.64,
    description: 'Award-winning singer-songwriter and global pop icon. Track confidence in Taylor Swift\'s album releases, tours, and cultural influence.',
  },
  {
    id: 22,
    ticker: 'DRAKE',
    name: 'Drake',
    category: 'Music Artists',
    basePrice: 192.37,
    description: 'Grammy-winning rapper and record producer. Trade confidence in Drake\'s chart dominance, album releases, and business ventures.',
  },
  {
    id: 23,
    ticker: 'KANYE',
    name: 'Kanye West',
    category: 'Music Artists',
    basePrice: 186.52,
    description: 'Influential rapper, producer, and fashion designer. Track confidence in Kanye West\'s music releases and brand partnerships.',
  },
  {
    id: 24,
    ticker: 'BUNNY',
    name: 'Bad Bunny',
    category: 'Music Artists',
    basePrice: 181.79,
    description: 'Global reggaeton and Latin trap artist. Trade confidence in Bad Bunny\'s chart success, tours, and cultural impact.',
  },
  {
    id: 25,
    ticker: 'TSOTT',
    name: 'Travis Scott',
    category: 'Music Artists',
    basePrice: 177.23,
    description: 'Hip-hop artist and record producer. Track confidence in Travis Scott\'s album releases, collaborations, and live performances.',
  },
  {
    id: 26,
    ticker: 'RODRI',
    name: 'Olivia Rodrigo',
    category: 'Music Artists',
    basePrice: 173.86,
    description: 'Rising pop star and songwriter. Trade confidence in Olivia Rodrigo\'s album success, chart performance, and growing fanbase.',
  },
  {
    id: 27,
    ticker: 'CARTI',
    name: 'Playboi Carti',
    category: 'Music Artists',
    basePrice: 169.41,
    description: 'Rapper and songwriter known for experimental sound. Track confidence in Playboi Carti\'s releases and influence on hip-hop culture.',
  },
  {
    id: 28,
    ticker: 'ISPCE',
    name: 'Ice Spice',
    category: 'Music Artists',
    basePrice: 165.98,
    description: 'Rising rapper and viral sensation. Trade confidence in Ice Spice\'s chart success, collaborations, and career growth.',
  },
  {
    id: 29,
    ticker: 'WKEND',
    name: 'The Weeknd',
    category: 'Music Artists',
    basePrice: 162.54,
    description: 'Grammy-winning singer, songwriter, and producer. Track confidence in The Weeknd\'s album releases, tours, and artistic evolution.',
  },
  {
    id: 30,
    ticker: 'DOJAC',
    name: 'Doja Cat',
    category: 'Music Artists',
    basePrice: 159.27,
    description: 'Singer, rapper, and songwriter. Trade confidence in Doja Cat\'s chart-topping hits, album releases, and social media presence.',
  },
  // Political Figures
  {
    id: 31,
    ticker: 'JBIDN',
    name: 'Joe Biden',
    category: 'Political Figures',
    basePrice: 141.23,
    description: 'Current president of the United States. Track confidence in Joe Biden\'s policy decisions, approval ratings, and political influence.',
  },
  {
    id: 32,
    ticker: 'KHARR',
    name: 'Kamala Harris',
    category: 'Political Figures',
    basePrice: 138.67,
    description: 'Vice President of the United States. Trade confidence in Kamala Harris\'s political standing, policy impact, and future prospects.',
  },
  {
    id: 33,
    ticker: 'RDESA',
    name: 'Ron DeSantis',
    category: 'Political Figures',
    basePrice: 135.89,
    description: 'Governor of Florida and political figure. Track confidence in Ron DeSantis\'s political influence, policy decisions, and electoral prospects.',
  },
  {
    id: 34,
    ticker: 'AOC',
    name: 'Alexandria Ocasio-Cortez',
    category: 'Political Figures',
    basePrice: 133.42,
    description: 'U.S. Representative and progressive political figure. Trade confidence in Alexandria Ocasio-Cortez\'s policy advocacy and political influence.',
  },
  {
    id: 35,
    ticker: 'VRAMA',
    name: 'Vivek Ramaswamy',
    category: 'Political Figures',
    basePrice: 130.76,
    description: 'Entrepreneur and political figure. Track confidence in Vivek Ramaswamy\'s political influence, policy positions, and public profile.',
  },
  {
    id: 36,
    ticker: 'NHALE',
    name: 'Nikki Haley',
    category: 'Political Figures',
    basePrice: 128.54,
    description: 'Former U.N. Ambassador and political figure. Trade confidence in Nikki Haley\'s political standing, policy influence, and electoral prospects.',
  },
  {
    id: 37,
    ticker: 'GNEWS',
    name: 'Gavin Newsom',
    category: 'Political Figures',
    basePrice: 126.18,
    description: 'Governor of California and political figure. Track confidence in Gavin Newsom\'s policy decisions, political influence, and future prospects.',
  },
  {
    id: 38,
    ticker: 'TCARS',
    name: 'Tucker Carlson',
    category: 'Political Figures',
    basePrice: 123.91,
    description: 'Media personality and political commentator. Trade confidence in Tucker Carlson\'s influence, media presence, and political impact.',
  },
  {
    id: 39,
    ticker: 'BSAND',
    name: 'Bernie Sanders',
    category: 'Political Figures',
    basePrice: 121.45,
    description: 'U.S. Senator and progressive political figure. Track confidence in Bernie Sanders\'s policy advocacy, political influence, and public support.',
  },
  // Startups
  {
    id: 40,
    ticker: 'CLUEL',
    name: 'Cluely',
    category: 'Startups',
    basePrice: 175.63,
    description: 'AI-powered startup focused on intelligent solutions. Trade confidence in Cluely\'s product development, market adoption, and growth trajectory.',
  },
  {
    id: 41,
    ticker: 'PERPL',
    name: 'Perplexity',
    category: 'Startups',
    basePrice: 188.92,
    description: 'AI search and research platform. Track confidence in Perplexity\'s user growth, product innovation, and competitive positioning.',
  },
  {
    id: 42,
    ticker: 'ABRID',
    name: 'Abridge',
    category: 'Startups',
    basePrice: 162.47,
    description: 'AI-powered medical transcription and documentation platform. Trade confidence in Abridge\'s healthcare technology adoption and market expansion.',
  },
  {
    id: 43,
    ticker: 'REPLI',
    name: 'Replit',
    category: 'Startups',
    basePrice: 195.28,
    description: 'Cloud-based development platform and AI coding assistant. Track confidence in Replit\'s developer adoption, platform growth, and product evolution.',
  },
  {
    id: 44,
    ticker: 'MERCU',
    name: 'Mercury',
    category: 'Startups',
    basePrice: 171.85,
    description: 'Banking platform for startups. Trade confidence in Mercury\'s financial services growth, customer acquisition, and market expansion.',
  },
  {
    id: 45,
    ticker: 'CHRAC',
    name: 'Character.AI',
    category: 'Startups',
    basePrice: 182.16,
    description: 'AI character conversation platform. Track confidence in Character.AI\'s user engagement, content creation, and platform development.',
  },
  {
    id: 46,
    ticker: 'LUMAI',
    name: 'Luma AI',
    category: 'Startups',
    basePrice: 169.74,
    description: '3D rendering and AI visualization technology. Trade confidence in Luma AI\'s product innovation, market adoption, and technology advancement.',
  },
  {
    id: 47,
    ticker: 'CURSO',
    name: 'Cursor',
    category: 'Startups',
    basePrice: 190.53,
    description: 'AI-powered code editor for developers. Track confidence in Cursor\'s developer adoption, product development, and market positioning.',
  },
  {
    id: 48,
    ticker: 'VAPI',
    name: 'Vapi',
    category: 'Startups',
    basePrice: 157.39,
    description: 'AI voice API platform. Trade confidence in Vapi\'s API adoption, developer ecosystem growth, and product innovation.',
  },
  {
    id: 49,
    ticker: 'ANYSP',
    name: 'Anysphere',
    category: 'Startups',
    basePrice: 164.82,
    description: 'AI development tools and infrastructure. Track confidence in Anysphere\'s product development, developer adoption, and market growth.',
  },
  // NFL Teams
  {
    id: 100,
    ticker: 'KCCHI',
    name: 'Kansas City Chiefs',
    category: 'NFL',
    basePrice: 185.42,
    description: 'NFL team based in Kansas City. Track confidence in the Chiefs\' performance, playoff prospects, and fan engagement.',
  },
  {
    id: 101,
    ticker: 'BUFBI',
    name: 'Buffalo Bills',
    category: 'NFL',
    basePrice: 178.93,
    description: 'NFL team based in Buffalo. Trade confidence in the Bills\' season performance, playoff chances, and team success.',
  },
  {
    id: 102,
    ticker: 'BALRA',
    name: 'Baltimore Ravens',
    category: 'NFL',
    basePrice: 176.58,
    description: 'NFL team based in Baltimore. Track confidence in the Ravens\' performance, roster strength, and championship potential.',
  },
  {
    id: 103,
    ticker: 'CINBE',
    name: 'Cincinnati Bengals',
    category: 'NFL',
    basePrice: 174.21,
    description: 'NFL team based in Cincinnati. Trade confidence in the Bengals\' season outlook, player performance, and playoff aspirations.',
  },
  {
    id: 104,
    ticker: 'CLEBR',
    name: 'Cleveland Browns',
    category: 'NFL',
    basePrice: 165.87,
    description: 'NFL team based in Cleveland. Track confidence in the Browns\' performance, roster decisions, and season success.',
  },
  {
    id: 105,
    ticker: 'PITST',
    name: 'Pittsburgh Steelers',
    category: 'NFL',
    basePrice: 172.45,
    description: 'NFL team based in Pittsburgh. Trade confidence in the Steelers\' tradition, team performance, and playoff chances.',
  },
  {
    id: 106,
    ticker: 'HOUTE',
    name: 'Houston Texans',
    category: 'NFL',
    basePrice: 158.32,
    description: 'NFL team based in Houston. Track confidence in the Texans\' rebuilding process, draft picks, and future success.',
  },
  {
    id: 107,
    ticker: 'INDCO',
    name: 'Indianapolis Colts',
    category: 'NFL',
    basePrice: 163.79,
    description: 'NFL team based in Indianapolis. Trade confidence in the Colts\' performance, quarterback situation, and season outlook.',
  },
  {
    id: 108,
    ticker: 'JAXJA',
    name: 'Jacksonville Jaguars',
    category: 'NFL',
    basePrice: 161.24,
    description: 'NFL team based in Jacksonville. Track confidence in the Jaguars\' development, young talent, and competitive progress.',
  },
  {
    id: 109,
    ticker: 'TENTI',
    name: 'Tennessee Titans',
    category: 'NFL',
    basePrice: 159.68,
    description: 'NFL team based in Tennessee. Trade confidence in the Titans\' performance, coaching decisions, and playoff potential.',
  },
  {
    id: 110,
    ticker: 'DENBR',
    name: 'Denver Broncos',
    category: 'NFL',
    basePrice: 162.15,
    description: 'NFL team based in Denver. Track confidence in the Broncos\' roster moves, quarterback play, and season performance.',
  },
  {
    id: 111,
    ticker: 'LACCH',
    name: 'Los Angeles Chargers',
    category: 'NFL',
    basePrice: 170.56,
    description: 'NFL team based in Los Angeles. Trade confidence in the Chargers\' talent, playoff chances, and championship aspirations.',
  },
  {
    id: 112,
    ticker: 'LARAM',
    name: 'Los Angeles Rams',
    category: 'NFL',
    basePrice: 168.92,
    description: 'NFL team based in Los Angeles. Track confidence in the Rams\' roster construction, coaching, and competitive success.',
  },
  {
    id: 113,
    ticker: 'OAKRA',
    name: 'Las Vegas Raiders',
    category: 'NFL',
    basePrice: 164.38,
    description: 'NFL team based in Las Vegas. Trade confidence in the Raiders\' performance, team culture, and playoff prospects.',
  },
  {
    id: 114,
    ticker: 'DALCO',
    name: 'Dallas Cowboys',
    category: 'NFL',
    basePrice: 182.67,
    description: 'NFL team based in Dallas. Track confidence in the Cowboys\' performance, playoff success, and championship potential.',
  },
  {
    id: 115,
    ticker: 'NYGIA',
    name: 'New York Giants',
    category: 'NFL',
    basePrice: 157.43,
    description: 'NFL team based in New York. Trade confidence in the Giants\' rebuilding efforts, draft strategy, and future success.',
  },
  {
    id: 116,
    ticker: 'PHIEA',
    name: 'Philadelphia Eagles',
    category: 'NFL',
    basePrice: 180.34,
    description: 'NFL team based in Philadelphia. Track confidence in the Eagles\' performance, roster depth, and Super Bowl chances.',
  },
  {
    id: 117,
    ticker: 'WASCO',
    name: 'Washington Commanders',
    category: 'NFL',
    basePrice: 155.89,
    description: 'NFL team based in Washington. Trade confidence in the Commanders\' rebuild, new ownership, and team development.',
  },
  {
    id: 118,
    ticker: 'CHIBE',
    name: 'Chicago Bears',
    category: 'NFL',
    basePrice: 160.12,
    description: 'NFL team based in Chicago. Track confidence in the Bears\' quarterback development, roster building, and competitive progress.',
  },
  {
    id: 119,
    ticker: 'DETLI',
    name: 'Detroit Lions',
    category: 'NFL',
    basePrice: 173.56,
    description: 'NFL team based in Detroit. Trade confidence in the Lions\' resurgence, coaching success, and playoff performance.',
  },
  {
    id: 120,
    ticker: 'GBPA',
    name: 'Green Bay Packers',
    category: 'NFL',
    basePrice: 177.89,
    description: 'NFL team based in Green Bay. Track confidence in the Packers\' quarterback transition, team performance, and playoff chances.',
  },
  {
    id: 121,
    ticker: 'MINVI',
    name: 'Minnesota Vikings',
    category: 'NFL',
    basePrice: 166.78,
    description: 'NFL team based in Minnesota. Trade confidence in the Vikings\' performance, roster decisions, and competitive success.',
  },
  {
    id: 122,
    ticker: 'ATLFA',
    name: 'Atlanta Falcons',
    category: 'NFL',
    basePrice: 158.91,
    description: 'NFL team based in Atlanta. Track confidence in the Falcons\' rebuild, quarterback situation, and future prospects.',
  },
  {
    id: 123,
    ticker: 'CARPA',
    name: 'Carolina Panthers',
    category: 'NFL',
    basePrice: 152.34,
    description: 'NFL team based in Carolina. Trade confidence in the Panthers\' rebuilding process, draft picks, and team development.',
  },
  {
    id: 124,
    ticker: 'NOSAI',
    name: 'New Orleans Saints',
    category: 'NFL',
    basePrice: 167.45,
    description: 'NFL team based in New Orleans. Track confidence in the Saints\' performance, roster management, and playoff aspirations.',
  },
  {
    id: 125,
    ticker: 'TABUC',
    name: 'Tampa Bay Buccaneers',
    category: 'NFL',
    basePrice: 171.23,
    description: 'NFL team based in Tampa Bay. Trade confidence in the Buccaneers\' performance, quarterback situation, and competitive success.',
  },
  {
    id: 126,
    ticker: 'ARICA',
    name: 'Arizona Cardinals',
    category: 'NFL',
    basePrice: 154.67,
    description: 'NFL team based in Arizona. Track confidence in the Cardinals\' rebuild, draft strategy, and future development.',
  },
  {
    id: 127,
    ticker: 'SF49',
    name: 'San Francisco 49ers',
    category: 'NFL',
    basePrice: 179.56,
    description: 'NFL team based in San Francisco. Trade confidence in the 49ers\' roster talent, coaching, and Super Bowl potential.',
  },
  {
    id: 128,
    ticker: 'SEAHA',
    name: 'Seattle Seahawks',
    category: 'NFL',
    basePrice: 169.78,
    description: 'NFL team based in Seattle. Track confidence in the Seahawks\' performance, quarterback play, and playoff chances.',
  },
  {
    id: 129,
    ticker: 'NEAT',
    name: 'New England Patriots',
    category: 'NFL',
    basePrice: 163.12,
    description: 'NFL team based in New England. Trade confidence in the Patriots\' rebuild, coaching decisions, and future success.',
  },
  {
    id: 130,
    ticker: 'NYJE',
    name: 'New York Jets',
    category: 'NFL',
    basePrice: 165.89,
    description: 'NFL team based in New York. Track confidence in the Jets\' quarterback situation, roster talent, and competitive progress.',
  },
  {
    id: 131,
    ticker: 'MIAOL',
    name: 'Miami Dolphins',
    category: 'NFL',
    basePrice: 175.34,
    description: 'NFL team based in Miami. Trade confidence in the Dolphins\' offensive performance, playoff chances, and team success.',
  },
  // NBA Teams
  {
    id: 200,
    ticker: 'BOSCE',
    name: 'Boston Celtics',
    category: 'NBA',
    basePrice: 195.42,
    description: 'NBA team based in Boston. Track confidence in the Celtics\' performance, playoff prospects, and championship potential.',
  },
  {
    id: 201,
    ticker: 'MILBU',
    name: 'Milwaukee Bucks',
    category: 'NBA',
    basePrice: 192.67,
    description: 'NBA team based in Milwaukee. Trade confidence in the Bucks\' roster talent, star players, and title chances.',
  },
  {
    id: 202,
    ticker: 'DENNU',
    name: 'Denver Nuggets',
    category: 'NBA',
    basePrice: 190.34,
    description: 'NBA team based in Denver. Track confidence in the Nuggets\' championship core, coaching, and competitive success.',
  },
  {
    id: 203,
    ticker: 'PHOEN',
    name: 'Phoenix Suns',
    category: 'NBA',
    basePrice: 188.56,
    description: 'NBA team based in Phoenix. Trade confidence in the Suns\' star power, roster depth, and playoff performance.',
  },
  {
    id: 204,
    ticker: 'LALAK',
    name: 'Los Angeles Lakers',
    category: 'NBA',
    basePrice: 186.93,
    description: 'NBA team based in Los Angeles. Track confidence in the Lakers\' legacy, star players, and championship aspirations.',
  },
  {
    id: 205,
    ticker: 'GSWAR',
    name: 'Golden State Warriors',
    category: 'NBA',
    basePrice: 184.78,
    description: 'NBA team based in San Francisco. Trade confidence in the Warriors\' dynasty, shooting, and title contention.',
  },
  {
    id: 206,
    ticker: 'PHI76',
    name: 'Philadelphia 76ers',
    category: 'NBA',
    basePrice: 182.15,
    description: 'NBA team based in Philadelphia. Track confidence in the 76ers\' star talent, team chemistry, and playoff success.',
  },
  {
    id: 207,
    ticker: 'MIAHE',
    name: 'Miami Heat',
    category: 'NBA',
    basePrice: 180.42,
    description: 'NBA team based in Miami. Trade confidence in the Heat\'s culture, coaching, and playoff resilience.',
  },
  {
    id: 208,
    ticker: 'DALMA',
    name: 'Dallas Mavericks',
    category: 'NBA',
    basePrice: 178.89,
    description: 'NBA team based in Dallas. Track confidence in the Mavericks\' star duo, offensive firepower, and playoff potential.',
  },
  {
    id: 209,
    ticker: 'CLELA',
    name: 'Cleveland Cavaliers',
    category: 'NBA',
    basePrice: 176.34,
    description: 'NBA team based in Cleveland. Trade confidence in the Cavaliers\' young core, development, and competitive progress.',
  },
  {
    id: 210,
    ticker: 'NYNKE',
    name: 'New York Knicks',
    category: 'NBA',
    basePrice: 174.67,
    description: 'NBA team based in New York. Track confidence in the Knicks\' rebuild, roster moves, and playoff chances.',
  },
  {
    id: 211,
    ticker: 'LACLI',
    name: 'Los Angeles Clippers',
    category: 'NBA',
    basePrice: 172.56,
    description: 'NBA team based in Los Angeles. Trade confidence in the Clippers\' star talent, depth, and championship window.',
  },
  {
    id: 212,
    ticker: 'OKCTH',
    name: 'Oklahoma City Thunder',
    category: 'NBA',
    basePrice: 170.23,
    description: 'NBA team based in Oklahoma City. Track confidence in the Thunder\'s young stars, rebuild, and future potential.',
  },
  {
    id: 213,
    ticker: 'MINWO',
    name: 'Minnesota Timberwolves',
    category: 'NBA',
    basePrice: 168.45,
    description: 'NBA team based in Minnesota. Trade confidence in the Timberwolves\' roster construction and playoff performance.',
  },
  {
    id: 214,
    ticker: 'SACKI',
    name: 'Sacramento Kings',
    category: 'NBA',
    basePrice: 166.78,
    description: 'NBA team based in Sacramento. Track confidence in the Kings\' offensive system, young talent, and competitive growth.',
  },
  {
    id: 215,
    ticker: 'NOPEL',
    name: 'New Orleans Pelicans',
    category: 'NBA',
    basePrice: 164.92,
    description: 'NBA team based in New Orleans. Trade confidence in the Pelicans\' young stars, depth, and playoff aspirations.',
  },
  {
    id: 216,
    ticker: 'ATLHA',
    name: 'Atlanta Hawks',
    category: 'NBA',
    basePrice: 162.34,
    description: 'NBA team based in Atlanta. Track confidence in the Hawks\' backcourt, roster moves, and playoff contention.',
  },
  {
    id: 217,
    ticker: 'CHIBU',
    name: 'Chicago Bulls',
    category: 'NBA',
    basePrice: 160.67,
    description: 'NBA team based in Chicago. Trade confidence in the Bulls\' roster, coaching, and competitive direction.',
  },
  {
    id: 218,
    ticker: 'TORRA',
    name: 'Toronto Raptors',
    category: 'NBA',
    basePrice: 158.45,
    description: 'NBA team based in Toronto. Track confidence in the Raptors\' rebuild, young talent, and future development.',
  },
  {
    id: 219,
    ticker: 'INDIA',
    name: 'Indiana Pacers',
    category: 'NBA',
    basePrice: 156.78,
    description: 'NBA team based in Indiana. Trade confidence in the Pacers\' fast-paced offense, young core, and growth.',
  },
  {
    id: 220,
    ticker: 'ORLMA',
    name: 'Orlando Magic',
    category: 'NBA',
    basePrice: 154.56,
    description: 'NBA team based in Orlando. Track confidence in the Magic\'s young talent, defensive identity, and rebuild progress.',
  },
  {
    id: 221,
    ticker: 'WASWI',
    name: 'Washington Wizards',
    category: 'NBA',
    basePrice: 152.34,
    description: 'NBA team based in Washington. Trade confidence in the Wizards\' rebuild, draft strategy, and future direction.',
  },
  {
    id: 222,
    ticker: 'CHAHO',
    name: 'Charlotte Hornets',
    category: 'NBA',
    basePrice: 150.67,
    description: 'NBA team based in Charlotte. Track confidence in the Hornets\' young stars, development, and competitive progress.',
  },
  {
    id: 223,
    ticker: 'DETPI',
    name: 'Detroit Pistons',
    category: 'NBA',
    basePrice: 148.45,
    description: 'NBA team based in Detroit. Trade confidence in the Pistons\' rebuild, young core, and future potential.',
  },
  {
    id: 224,
    ticker: 'BROKE',
    name: 'Brooklyn Nets',
    category: 'NBA',
    basePrice: 146.78,
    description: 'NBA team based in Brooklyn. Track confidence in the Nets\' rebuild, roster moves, and competitive direction.',
  },
  {
    id: 225,
    ticker: 'UTAJA',
    name: 'Utah Jazz',
    category: 'NBA',
    basePrice: 144.56,
    description: 'NBA team based in Utah. Trade confidence in the Jazz\'s rebuild, young talent, and development strategy.',
  },
  {
    id: 226,
    ticker: 'PORTR',
    name: 'Portland Trail Blazers',
    category: 'NBA',
    basePrice: 142.34,
    description: 'NBA team based in Portland. Track confidence in the Trail Blazers\' rebuild, draft picks, and future direction.',
  },
  {
    id: 227,
    ticker: 'HOURO',
    name: 'Houston Rockets',
    category: 'NBA',
    basePrice: 140.67,
    description: 'NBA team based in Houston. Trade confidence in the Rockets\' young core, development, and rebuild progress.',
  },
  {
    id: 228,
    ticker: 'MEMGR',
    name: 'Memphis Grizzlies',
    category: 'NBA',
    basePrice: 138.45,
    description: 'NBA team based in Memphis. Track confidence in the Grizzlies\' young stars, culture, and competitive potential.',
  },
  {
    id: 229,
    ticker: 'SANSP',
    name: 'San Antonio Spurs',
    category: 'NBA',
    basePrice: 136.78,
    description: 'NBA team based in San Antonio. Trade confidence in the Spurs\' rebuild, young talent, and future development.',
  },
  // Prediction Markets
  {
    id: 300,
    ticker: 'KALSH',
    name: 'Kalshi',
    category: 'Prediction Markets',
    basePrice: 175.00,
    description: 'US-regulated prediction market platform. Trade confidence in Kalshi\'s user growth, market expansion, and regulatory success.',
  },
  {
    id: 301,
    ticker: 'POLYM',
    name: 'Polymarket',
    category: 'Prediction Markets',
    basePrice: 168.45,
    description: 'Decentralized prediction market with crypto-backed markets. Track confidence in Polymarket\'s trading volume, platform adoption, and market leadership.',
  },
  {
    id: 302,
    ticker: 'PREDI',
    name: 'PredictIt',
    category: 'Prediction Markets',
    basePrice: 162.92,
    description: 'US political prediction market operated by Victoria University. Trade confidence in PredictIt\'s political market dominance and user engagement.',
  },
  {
    id: 303,
    ticker: 'BETFA',
    name: 'Betfair',
    category: 'Prediction Markets',
    basePrice: 155.38,
    description: 'UK-based betting exchange with prediction market features. Track confidence in Betfair\'s market liquidity, user base, and platform innovation.',
  },
  {
    id: 304,
    ticker: 'SMARK',
    name: 'Smarkets',
    category: 'Prediction Markets',
    basePrice: 148.15,
    description: 'UK betting exchange platform. Trade confidence in Smarkets\' market share, technology, and competitive positioning.',
  },
  {
    id: 305,
    ticker: 'AUGUR',
    name: 'Augur',
    category: 'Prediction Markets',
    basePrice: 142.67,
    description: 'Ethereum-based decentralized prediction market. Track confidence in Augur\'s protocol adoption, trading volume, and blockchain innovation.',
  },
  {
    id: 306,
    ticker: 'GNOSI',
    name: 'Gnosis',
    category: 'Prediction Markets',
    basePrice: 136.23,
    description: 'Ethereum ecosystem prediction market platform. Trade confidence in Gnosis\'s platform development, user adoption, and DeFi integration.',
  },
  {
    id: 307,
    ticker: 'OMEN',
    name: 'Omen',
    category: 'Prediction Markets',
    basePrice: 129.89,
    description: 'Gnosis-based prediction market platform. Track confidence in Omen\'s market growth, user experience, and platform features.',
  },
  {
    id: 308,
    ticker: 'ZEITG',
    name: 'Zeitgeist',
    category: 'Prediction Markets',
    basePrice: 123.56,
    description: 'Polkadot-based prediction market platform. Trade confidence in Zeitgeist\'s cross-chain capabilities, user adoption, and ecosystem growth.',
  },
  {
    id: 309,
    ticker: 'PLOTX',
    name: 'PlotX',
    category: 'Prediction Markets',
    basePrice: 117.12,
    description: 'DeFi prediction market platform. Track confidence in PlotX\'s market volume, tokenomics, and platform development.',
  },
  {
    id: 310,
    ticker: 'REALI',
    name: 'Reality.eth',
    category: 'Prediction Markets',
    basePrice: 110.78,
    description: 'Ethereum-based prediction market platform. Trade confidence in Reality.eth\'s oracle accuracy, market creation, and user engagement.',
  },
  {
    id: 311,
    ticker: 'STOX',
    name: 'Stox',
    category: 'Prediction Markets',
    basePrice: 104.34,
    description: 'Ethereum-based prediction market platform. Track confidence in Stox\'s platform features, market liquidity, and user growth.',
  },
  {
    id: 312,
    ticker: 'CATNI',
    name: 'Catnip Exchange',
    category: 'Prediction Markets',
    basePrice: 98.00,
    description: 'Prediction market aggregator and interface. Trade confidence in Catnip\'s user experience, market aggregation, and platform adoption.',
  },
  {
    id: 313,
    ticker: 'MANIF',
    name: 'Manifold Markets',
    category: 'Prediction Markets',
    basePrice: 91.67,
    description: 'Play money prediction market with high engagement. Track confidence in Manifold Markets\' community growth, platform features, and user retention.',
  },
  {
    id: 314,
    ticker: 'METAC',
    name: 'Metaculus',
    category: 'Prediction Markets',
    basePrice: 85.23,
    description: 'Forecasting platform for predictions and analysis. Trade confidence in Metaculus\'s forecasting accuracy, user base, and platform development.',
  },
  {
    id: 315,
    ticker: 'GOODJ',
    name: 'Good Judgment Project',
    category: 'Prediction Markets',
    basePrice: 78.89,
    description: 'Forecasting platform for accurate predictions. Track confidence in Good Judgment Project\'s forecasting performance, research, and platform growth.',
  },
  {
    id: 316,
    ticker: 'HYPER',
    name: 'Hypermind',
    category: 'Prediction Markets',
    basePrice: 72.45,
    description: 'Forecasting platform for predictions and analysis. Trade confidence in Hypermind\'s forecasting capabilities, user engagement, and market presence.',
  },
  {
    id: 317,
    ticker: 'NUMER',
    name: 'Numerai',
    category: 'Prediction Markets',
    basePrice: 66.12,
    description: 'Hedge fund with prediction market elements. Track confidence in Numerai\'s model performance, tokenomics, and fund returns.',
  },
  {
    id: 318,
    ticker: 'KLERO',
    name: 'Kleros',
    category: 'Prediction Markets',
    basePrice: 59.78,
    description: 'Dispute resolution platform with prediction elements. Trade confidence in Kleros\'s dispute resolution accuracy, token value, and platform adoption.',
  },
  {
    id: 319,
    ticker: 'FOREC',
    name: 'Forecaster',
    category: 'Prediction Markets',
    basePrice: 53.34,
    description: 'General prediction market platform. Track confidence in Forecaster\'s market creation, user base, and platform features.',
  },
  {
    id: 320,
    ticker: 'INFER',
    name: 'Infer',
    category: 'Prediction Markets',
    basePrice: 47.00,
    description: 'Prediction market platform for various markets. Trade confidence in Infer\'s platform development, user adoption, and market diversity.',
  },
  {
    id: 321,
    ticker: 'CROWD',
    name: 'Crowdwise',
    category: 'Prediction Markets',
    basePrice: 40.67,
    description: 'Community forecasting platform. Track confidence in Crowdwise\'s community engagement, forecasting accuracy, and platform growth.',
  },
  {
    id: 322,
    ticker: 'INSIG',
    name: 'Insight Prediction',
    category: 'Prediction Markets',
    basePrice: 34.23,
    description: 'Forecasting platform for predictions. Trade confidence in Insight Prediction\'s forecasting capabilities, user base, and platform features.',
  },
  {
    id: 323,
    ticker: 'CULTI',
    name: 'Cultivat3',
    category: 'Prediction Markets',
    basePrice: 32.89,
    description: 'Prediction market platform for various markets. Track confidence in Cultivat3\'s platform development, market creation, and user adoption.',
  },
  {
    id: 324,
    ticker: 'LAY3R',
    name: 'Lay3rs',
    category: 'Prediction Markets',
    basePrice: 31.45,
    description: 'Prediction market platform. Trade confidence in Lay3rs\'s platform features, user engagement, and market growth.',
  },
  {
    id: 325,
    ticker: 'POLYC',
    name: 'Polymarket Clone',
    category: 'Prediction Markets',
    basePrice: 30.12,
    description: 'Alternative prediction market platform. Track confidence in this platform\'s market share, features, and competitive positioning.',
  },
];

/**
 * Get entity by ID
 */
export const getEntityById = (id: number): MockEntity | undefined => {
  return MOCK_ENTITIES.find(entity => entity.id === id);
};

/**
 * Get entity by ticker
 */
export const getEntityByTicker = (ticker: string): MockEntity | undefined => {
  return MOCK_ENTITIES.find(entity => entity.ticker === ticker);
};

/**
 * Get all entities
 */
export const getAllEntities = (): MockEntity[] => {
  return MOCK_ENTITIES;
};

/**
 * Get entities by category
 */
export const getEntitiesByCategory = (category: string): MockEntity[] => {
  return MOCK_ENTITIES.filter(entity => entity.category === category);
};

/**
 * Get entity by name (case-insensitive)
 */
export const getEntityByName = (name: string): MockEntity | undefined => {
  return MOCK_ENTITIES.find(entity => 
    entity.name.toLowerCase() === name.toLowerCase()
  );
};

